### PR TITLE
Bug 1743873: data/bootstrap: extract ironic images from release image

### LINKED ISSUE #2090: baremetal: Migrate Ironic services to upstream images
The integration proposed via #2079 currently depends on some upstream images, because those in the openshift org are still in-progress.

This issue is to track moving to the correct OCP builds of these containers, and also similar to #2067 we should look at options to move to a staticpod, and perhaps also the MCO instead of the current systemd/script approach.

Ideally I'd like to not block the initial experimental support on this, so I'm raising this as a separate issue to #2060 and we'll address these issues via follow-up PRs

### PR DESCRIPTION
**Pull request by stbenjam**
startironic.sh now uses the ironic images specified in the release. In
order to do that, this change pulls out the code from bootkube to
get the images to it's own script, and adds a service that downloads the
release image so it only happens once.

fixes #2090

### CODE REVIEW

**Comment by stbenjam** [comment]
This now correctly extracts the release image:

release image:
```
  ironic-ipa-downloader                         sha256:1bfd9417e5b03ca611c09c805b925914d72441bf6ed7fd6f78f0a3edbdd425ea
  ironic-rhcos-downloader                       sha256:3ea6994ad12c057cfb2bcc4c5d228155f236e58ba9edf1294be6d14d1c72b169
```

podman ps:

```
0a034420fc82  quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:3ea6994ad12c057cfb2bcc4c5d228155f236e58ba9edf1294be6d14d1c72b169  /usr/local/bin/ge...  20 seconds ago      Up 20 seconds ago                     coreos-downloader
b81b932a7ee0  quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:1bfd9417e5b03ca611c09c805b925914d72441bf6ed7fd6f78f0a3edbdd425ea  /usr/local/bin/ge...  30 seconds ago      Exited (0) 24 seconds ago             ipa-downloader
```

File: data/data/bootstrap/baremetal/files/usr/local/bin/startironic.sh.template [hunk 1]
```diff
@@ -87,7 +86,6 @@ podman wait -i 1000 ipa-downloader
 podman wait -i 1000 coreos-downloader
 while ! curl --fail http://localhost/images/rhcos-ootpa-latest.qcow2.md5sum ; do sleep 1; done
 while ! curl --fail --head http://localhost/images/ironic-python-agent.initramfs ; do sleep 1; done
-while ! curl --fail --head http://localhost/images/ironic-python-agent.tar.headers ; do sleep 1; done
```
Comment (stbenjam) [inline data/data/bootstrap/baremetal/files/usr/local/bin/startironic.sh.template]: The [rhel based IPA image](https://github.com/openshift/ironic-ipa-downloader/blob/master/get-resource.sh#L16) doesn't produce this file, so the move to openshift images made this wait forever.

**Comment by metal3ci** [comment]
Build ABORTED, see build http://10.8.144.11:8080/job/dev-tools/1066/

**Comment by metal3ci** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/1067/

**Comment by stbenjam** [comment]
/retitle Bug 1743873: data/data/bootstrap: extract ironic images from release image

File: data/data/bootstrap/baremetal/files/usr/local/bin/startironic.sh.template [hunk 2]
```diff
@@ -1,13 +1,12 @@
...
-
 set -ex
 
-# We should switch to openshift builds of these images when ready ref
-# https://github.com/openshift/installer/issues/2090
-IRONIC_IMAGE=${IRONIC_IMAGE:-"quay.io/metal3-io/ironic:master"}
-IRONIC_INSPECTOR_IMAGE=${IRONIC_INSPECTOR_IMAGE:-"quay.io/metal3-io/ironic-inspector:master"}
-IPA_DOWNLOADER_IMAGE=${IPA_DOWNLOADER_IMAGE:-"quay.io/metal3-io/ironic-ipa-downloader:master"}
-COREOS_DOWNLOADER_IMAGE=${COREOS_DOWNLOADER_IMAGE:-"quay.io/openshift-metal3/rhcos-downloader:master"}
+. /usr/local/bin/release-image.sh
```
Comment (abhinavdahiya) [inline data/data/bootstrap/baremetal/files/usr/local/bin/startironic.sh.template]: cc @wking for bash knowledge..
 How is this different from `source`

File: data/data/bootstrap/files/usr/local/bin/release-image.sh.template [hunk 3]
```diff
@@ -0,0 +1,19 @@
+#!/usr/bin/env bash
+# release-image.sh is a helper library for interacting with a release image.
+
+if ! podman inspect {{.ReleaseImage}} &>/dev/null; then
```
Comment (abhinavdahiya) [inline data/data/bootstrap/files/usr/local/bin/release-image.sh.template]: If multiple services run this concurrently? what is the behavior?

File: data/data/bootstrap/files/usr/local/bin/bootkube.sh.template [hunk 4]
```diff
@@ -1,31 +1,16 @@
...
+. /usr/local/bin/release-image.sh
 
-# convert the release image pull spec to an "absolute" form if a digest is available - this is
-# safe to resolve after the actions above because podman will not pull the image once it is
-# locally available
-if ! release=$( podman inspect {{.ReleaseImage}} --format '{{"{{"}} index .RepoDigests 0 {{"}}"}}' ) || [[ -z "${release}" ]]; then
-	echo "Warning: Could not resolve release image to pull by digest" 2>&1
-	release="{{.ReleaseImage}}"
-fi
+mkdir --parents /etc/kubernetes/{manifests,bootstrap-configs,bootstrap-manifests}
```
Comment (abhinavdahiya) [inline data/data/bootstrap/files/usr/local/bin/bootkube.sh.template]: same as https://github.com/openshift/installer/pull/2234/files#r315922772

File: data/data/bootstrap/baremetal/files/usr/local/bin/startironic.sh.template (hunk 2 above)
Comment (stbenjam) [reply data/data/bootstrap/baremetal/files/usr/local/bin/startironic.sh.template]: They are identical in bash, AFAIK. I'm happy to switch to `source` if there's a preference. https://ss64.com/bash/source.html indicates it's more portable, but since we're specifying /bin/bash at the top I'm sure it';s fine.

File: data/data/bootstrap/files/usr/local/bin/bootkube.sh.template (hunk 4 above)
Comment (stbenjam) [reply data/data/bootstrap/files/usr/local/bin/bootkube.sh.template]: Can you clarify? I just moved this existing below sourcing release-image.sh, as I prefer to "import libraries" at the very top.

Comment (abhinavdahiya) [reply data/data/bootstrap/files/usr/local/bin/bootkube.sh.template]: mean for https://github.com/openshift/installer/pull/2234/files/956c2939e4cce7fc73130483deac2a91c6405c76#diff-ce82c1d8a44f7dfc41dfc024085ccfeeR4

File: data/data/bootstrap/baremetal/files/usr/local/bin/startironic.sh.template (hunk 2 above)
Comment (wking) [reply data/data/bootstrap/baremetal/files/usr/local/bin/startironic.sh.template]: +1 to @stbenjam's comment.  Here's [`.` in POSIX][1], and [here][2] is them saying `source` is unspecified.  But since we're using Bash, we don't have to be POSIX-compliant (although personally I prefer POSIX-compliance in places like this where it's no hardship).

[1]: http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#dot
[2]: http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_09_01_01

File: data/data/bootstrap/files/usr/local/bin/release-image.sh.template (hunk 3 above)
Comment (wking) [reply data/data/bootstrap/files/usr/local/bin/release-image.sh.template]: currently `podman` [pulls multiple copies in parallel][1].  containers/image#611 is long-running work around locks to make parallel pulls more efficient, but who knows if/when that will land.

[1]: https://github.com/containers/libpod/issues/1911#issue-386427543

Comment (stbenjam) [reply data/data/bootstrap/files/usr/local/bin/release-image.sh.template]: Looks like `flock` is available on RHCOS. I can write something off that, unless you have a preference for a different way

Comment (abhinavdahiya) [reply data/data/bootstrap/files/usr/local/bin/release-image.sh.template]: I was more interested making sure 2 runs of `podman` simultaneously wouldn't cause some corruption.. performance wasn't a concern..

Comment (stbenjam) [reply data/data/bootstrap/files/usr/local/bin/release-image.sh.template]: I don't think it causes any corruption issues, but if more than a couple things start sourcing this it could get ugly performance-wise.  Is there any objection to using something like `flock`? It's not very portable, though, but it is on RHCOS.  People also do hacky things with `mkdir` as it's guaranteed to be atomic.

```sh
(
    flock 9
    if ! release=$( podman inspect {{.ReleaseImage}} --format '{{"{{"}} index .RepoDigests 0 {{"}}"}}' ) || [[ -z "${release}" ]]; then
        echo "Warning: Could not resolve release image to pull by digest" 2>&1
        release="{{.ReleaseImage}}"
    fi
) 9>/var/lock/release-image.lock
```

Comment (wking) [reply data/data/bootstrap/files/usr/local/bin/release-image.sh.template]: I'm fine locking somehow in shell.  I'm also fine serializing these two services via some systems magic.  And because this is metal-only, I'm fine not locking at all too ;).  Ahbinav may be more opinionated.

Comment (markmc) [reply data/data/bootstrap/files/usr/local/bin/release-image.sh.template]: You could have a systemd service to pull the release image and have bootkube and ironic depend on it

Comment (stbenjam) [reply data/data/bootstrap/files/usr/local/bin/release-image.sh.template]: Thanks, @markmc, I think that is a nice approach. I've updated this PR.

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1078/

File: data/data/bootstrap/systemd/units/release-image.service.template [hunk 5]
```diff
@@ -0,0 +1,12 @@
+[Unit]
+Description=Downloads the OpenShift Release Image
+Wants=network-online.target
+After=network-online.target
+
+[Service]
+Type=oneshot
+RemainAfterExit=yes
+ExecStart=/usr/bin/podman pull "{{.ReleaseImage}}"
```
Comment (abhinavdahiya) [inline data/data/bootstrap/systemd/units/release-image.service.template]: podman pulls have known to fail due to various reasons. `oneshot` means that if we fail to pull release image because of transient failures, our bootstrapping will fail making it let resilient.

Comment (stbenjam) [reply data/data/bootstrap/systemd/units/release-image.service.template]: Sure, that makes sense, I updated this to follow the same pattern as bootkube to restart on failure + `set -e` + the conditional gating on a done file.

**Comment by dantrainor** [comment]
I was testing this as it related to #2249 and had a successful deployment.

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1081/

File: data/data/bootstrap/baremetal/systemd/units/ironic.service [hunk 6]
```diff
@@ -1,7 +1,7 @@
 [Unit]
 Description=Baremetal Deployment Ironic Services
-Wants=network-online.target crio.service
-After=network-online.target crio.service
+Wants=network-online.target crio.service release-image.service
```
Comment (abhinavdahiya) [inline data/data/bootstrap/baremetal/systemd/units/ironic.service]: > https://www.freedesktop.org/software/systemd/man/systemd.unit.html#Wants=

If the release-image fails transiently, this service will still start.. right? that means the podman inspect will keep failing.. creating noise


and we can't use Requires because of https://github.com/systemd/systemd/issues/1312

File: data/data/bootstrap/files/usr/local/bin/release-image-download.sh.template [hunk 7]
```diff
@@ -0,0 +1,5 @@
+#!/usr/bin/env bash
+set -e
+
+/usr/bin/podman pull "{{.ReleaseImage}}"
```
Comment (abhinavdahiya) [inline data/data/bootstrap/files/usr/local/bin/release-image-download.sh.template]: why the absolute path? can we rely on PATH?

Comment (abhinavdahiya) [reply data/data/bootstrap/files/usr/local/bin/release-image-download.sh.template]: also this not using `--quiet`

File: data/data/bootstrap/baremetal/systemd/units/ironic.service (hunk 6 above)
Comment (stbenjam) [reply data/data/bootstrap/baremetal/systemd/units/ironic.service]: Can you have a look at the updated approach? release-image is back to being a oneshot, but the retry logic is in the script. It will not complete until the image successfully downloads.  I do use `Requires` in this case, because release-image won't fail, it just keeps retrying.

release-image starts:

```
Aug 26 11:58:48 localhost systemd[1]: Starting Download the OpenShift Release Image...
Aug 26 11:58:48 localhost release-image-download.sh[1699]: Pulling registry.svc.ci.openshift.org/ocp/release:4.2...
Aug 26 11:58:48 localhost podman[1704]: 2019-08-26 11:58:48.997851388 +0000 UTC m=+0.232197590 system refresh
Aug 26 11:58:59 localhost podman[1704]: 2019-08-26 11:58:59.126738877 +0000 UTC m=+10.361085080 image pull  
Aug 26 11:58:59 localhost release-image-download.sh[1699]: c7a857fb2b0c9c7fc6a17efd848213dc1c1de874515e48286bbf907bccbf8055
Aug 26 11:58:59 localhost systemd[1]: Started Download the OpenShift Release Image.
```

And then immediately after finishing, bootkube starts:

```
Aug 26 11:58:59 localhost systemd[1]: Started Bootstrap a Kubernetes cluster.
```

**Comment by metal3ci** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/1094/

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1100/

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1101/

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1102/
