### PR TITLE
Bug 1715001: hack/build: Use BUILD_VERSION if non-empty

### LINKED ISSUE #1828: v4.1.0 reports a dirty version
# What happened?

Installer reported a dirty version.

# What you expected to happen?

Release binary should report a non-dirty version.

# How to reproduce it (as minimally and precisely as possible)?

First:

```
wget https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-install-linux-4.1.0.tar.gz  
```

```
tar -xvf openshift-install-linux-4.1.0.tar.gz                                                                      
README.md
openshift-install
```

Then:
```
./openshift-install version  
./openshift-install v4.1.0-201905212232-dirty
built from commit 71d8978039726046929729ad15302973e3da18ce
release image quay.io/openshift-release-dev/ocp-release@sha256:b8307ac0f3ec4ac86c3f3b52846425205022da52c16f56ec31cbe428501001d6
```

### PR DESCRIPTION
**Pull request by wking**
Like 3313c08266 (#1744), but for tags.  This should fix #1828:

```console
$ ./openshift-install version
./openshift-install v4.1.0-201905212232-dirty
...
```

Doozer [sets `SOURCE_GIT_TAG`][2] just like it sets `SOURCE_GIT_COMMIT`.

Fixes #1828.

[1]: https://github.com/openshift/installer/issues/1828
[2]: https://github.com/openshift/doozer/blob/a36e072a87d403c09519a1d0c9be4757f8bee941/doozerlib/distgit.py#L1229

### CODE REVIEW

**Comment by wking** [comment]
/hold

@sosiouxme is running this through doozer to see if it works, and we'll want to double-check the CI results to make sure the CI pipeline is handling it well too.

**Comment by sosiouxme** [comment]
doozer sets `SOURCE_GIT_TAG` using the tags from the source repo.
We need an env var that expresses the version and release being built (currently only set in the image labels).

**Comment by wking** [comment]
Looks like this is working in CI (by not changing anything vs. our previous code):

```
$ curl -s https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/1829/pull-ci-openshift-installer-master-e2e-aws/5977/artifacts/e2e-aws/installer/.openshift_install.log | head -n1
time="2019-06-06T20:00:26Z" level=debug msg="OpenShift Installer unreleased-master-1107-g6d4fda00d50911982ba2dfbfabc7930757ca8122-dirty"
```

We still need to figure out what variable doozer will set to hold the version being built.

**Comment by sosiouxme** [comment]
> We still need to figure out what variable doozer will set to hold the version being built.

@wking `BUILD_VERSION` and `BUILD_RELEASE` as it turns out.

http://pkgs.devel.redhat.com/cgit/containers/ose-installer/tree/Dockerfile?h=rhaos-4.1-rhel-7

**Comment by wking** [comment]
I've pushed 4932bd020 -> 59e43a3d8 to move us over to `BUILD_VERSION` and `BUILD_RELEASE`.

**Comment by wking** [comment]
[e2e-aws][1] had the external API load-balancer throttled:

```
level=error msg="Error: timeout while waiting for state to become 'active' (last state: 'provisioning', timeout: 10m0s)" level=error level=error msg=" on ../tmp/openshift-install-451751868/vpc/master-elb.tf line 19, in resource \"aws_lb\" \"api_external\":" level=error msg=" 19: resource \"aws_lb\" \"api_external\" {" 
```

/test e2e-aws

[1]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_installer/1829/pull-ci-openshift-installer-master-e2e-aws/7000

**Comment by wking** [comment]
CI is still happily unaffected:

```console
$ curl --compressed -s https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/1829/pull-ci-openshift-installer-master-e2e-aws/7008/artifacts/e2e-aws/installer/.openshift_install.log | head -n1
time="2019-08-01T19:05:51Z" level=debug msg="OpenShift Installer unreleased-master-1497-g7177dc92ef38ed7c4d8e1c144bd584736ee65def-dirty"
```

@sosiouxme, did you want to wash this through doozer to confirm it picks up your `BUILD_VERSION` or `BUILD_RELEASE`?

File: hack/build.sh [hunk 1]
```diff
@@ -32,7 +32,8 @@ fi
 
 MODE="${MODE:-release}"
 GIT_COMMIT="${SOURCE_GIT_COMMIT:-$(git rev-parse --verify 'HEAD^{commit}')}"
-LDFLAGS="${LDFLAGS} -X github.com/openshift/installer/pkg/version.Raw=$(git describe --always --abbrev=40 --dirty) -X github.com/openshift/installer/pkg/version.Commit=${GIT_COMMIT}"
+GIT_TAG="${BUILD_VERSION:-${BUILD_RELEASE:-$(git describe --always --abbrev=40 --dirty)}}"
```
Comment (sosiouxme) [inline hack/build.sh]: In my example we have `BUILD_VERSION=v4.1.9` and `BUILD_RELEASE=201907311355` -- they work together, not as alternatives. What you'll get here is
```
GIT_TAG=v4.1.9
```
In which case this would be less confusing:
```suggestion
GIT_TAG="${BUILD_VERSION:-$(git describe --always --abbrev=40 --dirty)}"
```
But I would think you'd want `v4.1.9-201907311355`. If so, then it'd be something like:
```suggestion
if [ -z "${BUILD_VERSION}" ] || [ -z "${BUILD_RELEASE" ]; then
    GIT_TAG=$(git describe --always --abbrev=40 --dirty)
else
    GIT_TAG="${BUILD_VERSION}-${BUILD_RELEASE}"
fi
```

Comment (wking) [reply hack/build.sh]: > ```diff
> -GIT_TAG="${BUILD_VERSION:-${BUILD_RELEASE:-$(git describe --always --abbrev=40 --dirty)}}"
> +GIT_TAG="${BUILD_VERSION:-$(git describe --always --abbrev=40 --dirty)}"
> ```

This is effectively what we have now, and it leads to:

```console
$ wget https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.1.8/openshift-install-linux-4.1.8.tar.gz
$ tar xf openshift-install-linux-4.1.8.tar.gz
$ ./openshift-install version
./openshift-install v4.1.8-201907241243-dirty
built from commit e8d7e37ea7655522ac8f6ede471fd1d3ebd1bcba
release image quay.io/openshift-release-dev/ocp-release@sha256:3ea2648231035c1a65e8d91fa818bb225a2815bc0d6abfc35063a11eaba8659f
```

That's fine, but the `-dirty` is distracting.  And if we know that the version is v4.1.8, who cares about the timestamp?  We only ever get a single 4.1.8 far enough along to show up in front of end-users, even if there's a build hiccup or some such that causes us to build multiple rounds with the same version internally.

> ```diff
> -GIT_TAG="${BUILD_VERSION:-${BUILD_RELEASE:-$(git describe --always --abbrev=40 --dirty)}}"
> +if [ -z "${BUILD_VERSION:-}" ] \|\| [ -z "${BUILD_RELEASE:-}" ]; then
> +  GIT_TAG=$(git describe --always --abbrev=40 --dirty)
> +else
> +  GIT_TAG="${BUILD_VERSION}-${BUILD_RELEASE}"
> +fi
> ```

If we have either `BUILD_VERSION` or `BUILD_RELEASE`, I'd rather use the one we have; not fall back to the local tag if one `BUILD_*` is missing.  [The doozer source][1] has separate conditionals for each, so I don't want to assume we'll always have both available.  As I said earlier in this comment, I expect `BUILD_VERSION` to be sufficiently unique on its own.  If it's missing, the timestamp `BUILD_RELEASE` is almost certain to *also* be sufficiently unique, although it loses the 4.1 vs. 4.2 etc. distinctions.

Is that sufficient motivation for using just `BUILD_VERSION`, falling back to just `BUILD_RELEASE`, falling back to just the local tag?  Or am I missing something?

[1]: https://gitlab.cee.redhat.com/openshift-art/tools/doozer/commit/b02114a0bb26bbb7f60f1cc484c17fc3172c6df4#8f42eb7865c4c8ea16b5ede36b478344f79c992d_1240_1246

Comment (sosiouxme) [reply hack/build.sh]: doozer has to accommodate 3.x and 4.x which have _very_ different schemes for RELEASE. It's common for it to be unknown in 3.x (assigned during the build process). That's the reason for the conditional (would not expect it ever to be empty in 4.x).

But there will never be a situation where BUILD_VERSION is not defined in an OCP build. If just the version is good enough for you, then there's no reason to bring BUILD_VERSION into it. There'll be no difference between
```
GIT_TAG="${BUILD_VERSION:-${BUILD_RELEASE:-$(git describe --always --abbrev=40 --dirty)}}"
```
and
```
GIT_TAG="${BUILD_VERSION:-$(git describe --always --abbrev=40 --dirty)}"
```

I don't think I understand where the -dirty is coming from if not the git command. I'll run a build for ya though just for funzies...

Comment (sosiouxme) [reply hack/build.sh]: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=22896476 is the build (wait for it...)

Comment (wking) [reply hack/build.sh]: > I don't think I understand where the -dirty is coming from if not the git command.

I think it is coming from the `git` command (because of a touched Dockerfile?), which is why I'd prefer not to be using `git` to extract the local tags when we're being called by doozer.

> If just the version is good enough for you, then there's no reason to bring `BUILD_VERSION` into it. 

Done with 59e43a3d8 -> dd7cff388.

While adjusting the commit message, I realized that using `${BUILD_VERSION}` instead of `${BUILD_VERSION}-${BUILD_RELEASE}` is going to mean a lot of nominally v4.2.0 installers for all of the 4.2 prereleases.  I'm fine with that, because we still have the source commit ID to look up the exact version used, but it makes me more open to using `${BUILD_VERSION}-${BUILD_RELEASE}` than I was earlier ;).

> https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=22896476 is the build...

Looks good:

```console
$ curl -s http://download.eng.bos.redhat.com/brewroot/work/tasks/6476/22896476/x86_64.log | grep ' GIT_TAG=v'
2019-08-02 21:12:27,911 - atomic_reactor.plugins.imagebuilder - INFO - + GIT_TAG=v4.2.0
```

**Comment by wking** [comment]
I'm comfortable with [the test results][1], even though those were against 59e43a3 and I've since pushed further updates.

/hold cancel

[1]: https://github.com/openshift/installer/pull/1829#discussion_r310314508

**Comment by sdodson** [comment]
@patrickdillon or @vrutkovs PTAL
