### PR TITLE
CORS-4266: Add generated DeepCopy implementations for pkg/types/installconfig

### LINKED ISSUE #256: InstallConfig Cannot Be Embedded in Kube Types Due to missing DeepCopyInto Methods
I've been working on re-using InstallConfig within Hive's ClusterDeployment CRD and run into some problems that could use discussion:

- Can't be used within a kube type due to missing kube generated methods (DeepCopyInto). Will need to be maintained as a full Kubernetes object for this to work. At present I'm copying your code, and getting codegen working in our code base, with a few tweaks that are required.
- Use of IPNet for CIDRs doesn't work in Kube. Need a custom type or string I believe.
- InstallConfig carries ObjectMeta which can trigger some things we don't necessarily want in our repo. (this one may not be a big deal)

Should the canonical source of the cluster config type live in the Installer? Would the config ever contain options that the installer ignored or did not act on? (and perhaps Hive or other actors would?) (I think the answer is probably "no" here)

How can we share defaulting and validation code? Ideally we want to inform an API caller their config is not valid without relying on the Installer to fail in a pod we're running. Quicker feedback will be important and ideally we should all be sharing the same code to do so.

Is InstallConfig appropriately named? Per last arch call we agreed it's not just an install time thing. Would ClusterConfig be more accurate?

Some options to clean this up:

(1) Keep InstallConfig in Installer. Hookup Kubernetes code gen, commit to all the guarantees required for the type going forward: treat as an externally facing API object that must to be greater than or equal to the serialization of any embedding format.

(2) Hand it over to Hive, lets us maintain the Kube generation and API contract, vendor into your repo. (I would propose a breakout of something like ClusterConfig in the Hive repo, and InstallConfig remaining in your repo and having fields ClusterConfig and Admin (which doesn't map nicely to kube secrets we'd use for this info)). 

(3) Place ClusterConfig definition directly into the core OpenShift API server. I don't know if this would fly but I kind of liked the idea, it makes it very official, we get API server for free and better options for versioning, validation and defaulting than CRDs, and it would signify how hard it is, or should be to change.

(4) Spin into a separate project and repo we all vendor.

Open to other suggestions. Please let me know what you think.

### PR DESCRIPTION
**Pull request by dlom**
Closes #256 (for real this time)
xref: [CORS-4266](https://issues.redhat.com//browse/CORS-4266)
See also: https://github.com/openshift/hive/pull/2731

Additionally, this PR removes the `UniqueItems` validator on the IP address tuples, as explained in the commit message

### CODE REVIEW

File: pkg/types/installconfig.go [hunk 1]
```diff
@@ -86,6 +86,7 @@ const (
 )
 
 //go:generate go run ../../vendor/sigs.k8s.io/controller-tools/cmd/controller-gen crd:crdVersions=v1 paths=. output:dir=../../data/data/
+//go:generate go run ../../vendor/k8s.io/code-generator/cmd/deepcopy-gen --output-file zz_generated.deepcopy.go ./...
```
Comment (dlom) [inline pkg/types/installconfig.go:89]: Here is where the generator is actually invoked.  This ties in with existing codegen, and `hack/verify_codegen.sh`

**Comment by dlom** [comment]
/retitle [CORS-4266](https://issues.redhat.com//browse/CORS-4266): Add generated DeepCopy implementations for pkg/types/installconfig

File: pkg/ipnet/ipnet_test.go [hunk 2]
```diff
@@ -56,3 +56,42 @@ func TestUnmarshal(t *testing.T) {
...
+		{IPNet: net.IPNet{
+			IP:   net.IP{192, 168, 0, 10},
+			Mask: net.IPv4Mask(255, 255, 255, 0),
+		}},
+	} {
+		t.Run(ipNetIn.String(), func(t *testing.T) {
+			t.Run("DeepCopyInto", func(t *testing.T) {
+				ipNetOut := &IPNet{IPNet: net.IPNet{
+					IP:   net.IP{10, 0, 0, 0},
+					Mask: net.IPv4Mask(255, 0, 0, 0),
```
Comment (patrickdillon) [inline pkg/ipnet/ipnet_test.go]: I don't understand this.. Is this seeding with an incorrect value, and it should be overwritten with the correct value?
Seems like it should just be empty (`&IPNet{}`)

File: pkg/ipnet/ipnet_test.go [hunk 3]
```diff
@@ -56,3 +56,42 @@ func TestUnmarshal(t *testing.T) {
...
+					t.Fatalf("%v != %v", ipNetOut, ipNetIn)
+				}
+
+				ipNetIn.IPNet = net.IPNet{
+					IP:   net.IP{192, 168, 10, 10},
+					Mask: net.IPv4Mask(255, 255, 255, 255),
+				}
+				if ipNetOut.String() == ipNetIn.String() {
+					t.Fatalf("%v (%q) == %v (%q)", ipNetOut, ipNetOut.String(), ipNetIn, ipNetIn.String())
+				}
```
Comment (patrickdillon) [inline pkg/ipnet/ipnet_test.go]: This assertion also seems a little weird. Can you double check this?

File: pkg/types/azure/doc.go [hunk 4]
```diff
@@ -1,5 +1,6 @@
 // Package azure contains Azure-specific structures for installer
 // configuration and management.
+// +k8s:deepcopy-gen=package
```
Comment (patrickdillon) [inline pkg/types/azure/doc.go:3]: does the annotation only need to be on a single file in the package? Typically `platform.go` is the "main" file for each platform, and prima face seems to mea better candidate than doc.go, though I'm open to doc.go if there's a rationale

**Review by patrickdillon — COMMENTED** [review]
This looks good. Left some minor comments, which I think should be addressed.

Regarding the last commit, removing uniqueitems I think that's fine. I reviewed the validation code and we have validation in place that ensures if 2 IPs are provided, one must be ipv4 and one ipv6, so therefore they must be unique. i.e. the validation is redundant and already in place.

File: pkg/types/azure/doc.go (hunk 4 above)
Comment (patrickdillon) [reply pkg/types/azure/doc.go:3]: > All generation is governed by comment tags in the source. Any package may request DeepCopy generation by including a comment in the file-comments of a doc.go file, of the form: 

shows what I know!

File: pkg/ipnet/ipnet_test.go (hunk 2 above)
Comment (dlom) [reply pkg/ipnet/ipnet_test.go]: I'm not sure, I copied this implementation and the associated unit tests from https://github.com/openshift/installer/pull/276

**Comment by dlom** [comment]
@patrickdillon Thank you, this is ready for a final review now

**Comment by patrickdillon** [comment]
/approve
/lgtm

will be verified by verify-codegen, which timedout on the most recent run

**Comment by dlom** [comment]
@patrickdillon I have a manual backport of these commits here (https://github.com/dlom/installer/tree/add-deepcopy-to-types-1.4.19-ec5), is it possible to get that branch in here and with a new tag for us to use?

**Comment by dlom** [comment]
@patrickdillon this needs a re-stamp from the rebase

**Comment by patrickdillon** [comment]
doh meant to
/lgtm

**Comment by 2uasimojo** [comment]
Something weird happening with tide here.

/retest-required

**Comment by 2uasimojo** [comment]
Oh. Tide is okay. This needs to be "verified". I think that's triggered by a card state?

**Comment by tthvo** [comment]
I think the e2e failures are valid. Since https://github.com/openshift/installer/pull/10075 is merged, we need to run another re-generate here.

For example, [ci/prow/e2e-azure-ovn-shared-vpc](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_installer/10025/pull-ci-openshift-installer-main-e2e-azure-ovn-shared-vpc/1990911095962865664):

```
 pkg/types/gcp/zz_generated.deepcopy.go:254:8: in.ServiceEndpoints undefined (type *Platform has no field or method ServiceEndpoints)
pkg/types/gcp/zz_generated.deepcopy.go:255:18: in.ServiceEndpoints undefined (type *Platform has no field or method ServiceEndpoints)
pkg/types/gcp/zz_generated.deepcopy.go:255:41: out.ServiceEndpoints undefined (type *Platform has no field or method ServiceEndpoints) 
```

/hold

**Comment by dlom** [comment]
How did some pass and some fail? :exploding_head: 

edit: and `verify-codegen` should have complained

**Comment by tthvo** [comment]
> How did some pass and some fail? 🤯
> 
> edit: and `verify-codegen` should have complained

I suspect those "passed" jobs could be stale pre-submit results that haven't been rerun :shrug: Let's see again...

/hold cancel

**Comment by patrickdillon** [comment]
This is caught in retest hell.
