### PR TITLE
pkg/tfvars: Pull from []Machine instead of InstallConfig

### LINKED ISSUE #671: how to set up aws instances: instanceType and deviceMapping?
# Version

```console
$ ./bin/openshift-install version
./bin/openshift-install v0.3.0-208-g54b49cdf0fb6d1150c7a9d4102e2b785d5a0344d
Terraform v0.11.8

Your version of Terraform is out of date! The latest version
is 0.11.10. You can update by downloading from www.terraform.io/downloads.html
```

# Platform (aws|libvirt|openstack):

aws

# What happened?

I would like to know how to set up the instance type and device mapping
```
$ bin/openshift-install create manifests
$ vi ./tectonic/99_openshift-cluster-api_master-machines.yaml
...
        instanceType: m5.xlarge

$ bin/openshift-install create cluster --log-level=debug
```
1. the modification on `instanceType` did not have impact. The created instances are still with the default `t2.medium`
2. need a way to set up device mapping
```
$ oc version
oc v4.0.0-alpha.0+a148deb-572
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://hongkliu-api.devcluster.openshift.com:6443
kubernetes v1.11.0+d4cacc0

$ oc explain machine
error: Couldn't find resource for "cluster.k8s.io/v1alpha1, Kind=Machine"
```

# What you expected to happen?

Would like to see how to set those properties up for aws instances.

# How to reproduce it (as minimally and precisely as possible)?

See above.

```console
$ your-commands-here
```

# Anything else we need to know?

This is more of questions instead of bug/issue report.
Would like to know how to do things with installer.

# References

- enter text here.

### PR DESCRIPTION
**Pull request by wking**
The previous implementation pulled from the install-config, but that missed downstream changes like AWS instance type defaults being applied in `pkg/asset/machines`.  With this commit, we pull that information from the cluster-API types, since they're the last touch point for that data.  The remaining information still comes from the `InstallConfig`, but I've split it into explicit arguments to avoid confusion about where data is coming from when `InstallConfig`'s machine pools, etc. overlap with `clusterapi.Machine` fields.

This is a WIP because there are some FIXMEs around cluster-API support for some of the settings we're currently configuring in `InstallConfig` machine pools.

Fixes #671.

### CODE REVIEW

File: pkg/asset/cluster/tfvars.go [hunk 1]
```diff
@@ -36,24 +40,76 @@ func (t *TerraformVariables) Dependencies() []asset.Asset {
...
 
-	bootstrapIgn := string(bootstrap.Files()[0].Data)
+	bootstrapIgn := string(bootstrapIgnAsset.Files()[0].Data)
 
-	masterIgn := string(master.Files()[0].Data)
+	masterIgn := string(masterIgnAsset.Files()[0].Data)
 
-	data, err := tfvars.TFVars(installConfig.Config, bootstrapIgn, masterIgn)
+	var mastersList metav1.List
+	err := yaml.Unmarshal(mastersAsset.MachinesRaw, &mastersList)
```
Comment (abhinavdahiya) [inline pkg/asset/cluster/tfvars.go]: can we change the master asset to be typed.. no need for this unamrshal? There were no consumers for that before, might be good time to add it...

File: pkg/asset/cluster/tfvars.go [hunk 2]
```diff
@@ -36,24 +40,76 @@ func (t *TerraformVariables) Dependencies() []asset.Asset {
...
+
+	var vpcCIDR string
+	if installConfig.Config.Platform.AWS != nil {
+		vpcCIDR = installConfig.Config.Platform.AWS.VPCCIDRBlock
+	}
+
+	var bridge string
+	var image string
+	if installConfig.Config.Platform.Libvirt != nil {
+		vpcCIDR = installConfig.Config.Platform.Libvirt.Network.IPRange
```
Comment (abhinavdahiya) [inline pkg/asset/cluster/tfvars.go]: maybe name it same or keep them separate.

File: pkg/asset/cluster/tfvars.go [hunk 3]
```diff
@@ -36,24 +40,76 @@ func (t *TerraformVariables) Dependencies() []asset.Asset {
...
+		bridge = installConfig.Config.Platform.Libvirt.Network.IfName
+		if installConfig.Config.Platform.Libvirt.DefaultMachinePlatform == nil {
```
Comment (abhinavdahiya) [inline pkg/asset/cluster/tfvars.go]: Hmm, we should do something like we do in Master Asset. this is not sustainable.

File: pkg/asset/cluster/tfvars.go [hunk 4]
```diff
@@ -36,24 +40,76 @@ func (t *TerraformVariables) Dependencies() []asset.Asset {
...
+		image = installConfig.Config.Platform.Libvirt.DefaultMachinePlatform.Image
+	}
+
+	var cloud string
+	if installConfig.Config.Platform.OpenStack != nil {
+		vpcCIDR = installConfig.Config.Platform.OpenStack.NetworkCIDRBlock
+		cloud = installConfig.Config.Platform.OpenStack.Cloud
+	}
+
+	data, err := tfvars.TFVars(
```
Comment (abhinavdahiya) [inline pkg/asset/cluster/tfvars.go]: This function is combining options from multiple platforms.. can we just switch to platform based ones?

File: pkg/tfvars/aws/aws.go [hunk 5]
```diff
@@ -54,3 +61,35 @@ type Worker struct {
 	CustomSubnets map[string]string `json:"aws_worker_custom_subnets,omitempty"`
 	IAMRoleName   string            `json:"aws_worker_iam_role_name,omitempty"`
 }
+
+// TFVars generates AWS-specific Terraform variables.
+func TFVars(config []byte, vpcCIDR string) (*AWS, error) {
```
Comment (abhinavdahiya) [inline pkg/tfvars/aws/aws.go]: shuuld consume type not config bytes.

File: pkg/tfvars/libvirt/libvirt.go [hunk 6]
```diff
@@ -22,34 +26,44 @@ type Network struct {
 	IPRange string `json:"libvirt_ip_range,omitempty"`
 }
 
-// TFVars fills in computed Terraform variables.
-func (l *Libvirt) TFVars(masterCount int) error {
-	_, network, err := net.ParseCIDR(l.Network.IPRange)
+// TFVars generates libvirt-specific Terraform variables.
+func TFVars(config []byte, image string, vpcCIDR string, bridge string, masterCount int) (*Libvirt, error) {
```
Comment (abhinavdahiya) [inline pkg/tfvars/libvirt/libvirt.go]: should consume type not config bytes.
vpcCidr is nt suitable in libvirt.

File: pkg/tfvars/tfvars.go [hunk 7]
```diff
@@ -23,102 +21,62 @@ type config struct {
...
-		case "worker":
-			if m.Platform.AWS != nil {
-				config.AWS.Worker = aws.Worker{
-					IAMRoleName: m.Platform.AWS.IAMRoleName,
-				}
-			}
-		default:
-			return nil, errors.Errorf("unrecognized machine pool %q", m.Name)
-		}
+	machine := masters[0]
```
Comment (abhinavdahiya) [inline pkg/tfvars/tfvars.go]: This entire section should not use this `map[string]interface{}`. each provider should have schema.

File: pkg/asset/cluster/tfvars.go (hunk 1 above)
Comment (wking) [reply pkg/asset/cluster/tfvars.go]: > can we change the master asset to be typed...

I'm fine with the `Unmarshal` here, especially while [we continue to generate the OpenStack machines via template][1].  But I can add a YAML unmarshal in `*Master.Generate` for the OpenStack machines if you'd rather push this up there and store structured information on the asset.

[1]: https://github.com/openshift/installer/blob/17ffd16d917ddbb7d1f0eeff9833289bff560437/pkg/asset/machines/master.go#L133

File: pkg/asset/cluster/tfvars.go (hunk 2 above)
Comment (wking) [reply pkg/asset/cluster/tfvars.go]: > maybe name such that we can keep it same or keep them separate.

These are all the same idea.  And personally, I'd be fine promoting all of these to an `InstallConfig.Networking` property (alongside `ServiceCIDR` and `ClusterNetworks`) to make it more obvious that it's a cross-platform idea.  Maybe `nodeCIDR`?  `machineCIDR`?

File: pkg/asset/cluster/tfvars.go (hunk 3 above)
Comment (wking) [reply pkg/asset/cluster/tfvars.go]: > Hmm, we should do something like we do in Master Asset. this is not sustainable.

Extracting the image here?  Our Terraform handling is currently broken by assuming a single libvirt image, while the Go types allow for per-machine(-set) images.  Eventually we're going to either want to remove the flexibility from our Go (if we want to go down the "everyone will use RHCOS and won't care about the details" path) or add it to our Terraform (if we want want to go down the "folks may want to choose on a per-machine(-set) basis" path).  I'm fine punting on that for this PR, but let me know if you have clarity on the long-term direction (or if you think it needs to be handled here).

File: pkg/asset/cluster/tfvars.go (hunk 4 above)
Comment (wking) [reply pkg/asset/cluster/tfvars.go]: > ... can we just switch to platform based ones?

Sure.  In #556 I have separate assets for the per-platform Terraform variables (like [this][1]).  But #556 requires one asset per file and allows me to dynamically declare per-platform dependencies (like [this][2]).  How did you want me to fit that into the current asset structure?  Should I add another file to `TerraformVariables` or create a new asset?  Should I use a platform-specific filename like I do in #556 (e.g. see [the generated variables][3]) or a generic name like `platform.auto.tfvars`?

[1]: https://github.com/openshift/installer/blob/71bd435b2c2e9ae8885c7dc21797bf2aef634c66/pkg/installerassets/aws/terraform.go
[2]: https://github.com/openshift/installer/blob/71bd435b2c2e9ae8885c7dc21797bf2aef634c66/pkg/installerassets/cluster.go#L30
[3]: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/556/pull-ci-openshift-installer-master-e2e-aws/1843/artifacts/e2e-aws/installer/terraform/aws-terraform.auto.tfvars

**Comment by wking** [comment]
Rebased onto master with 270da62 -> 931b281.

File: pkg/tfvars/tfvars.go (hunk 7 above)
Comment (wking) [reply pkg/tfvars/tfvars.go]: > This entire section should not use this `map[string]interface{}`. each provider should have schema.

The input master `*Machine` instances already specify the platform via the provider's `apiVersion` field (e.g. `aws.cluster.k8s.io/v1alpha1`), so switching on that seemed like a DRY way to determine which platform to use to translate the `Machine` content into Terraform.  It also allows me to push the platform-specific provider unpacking down into the provider-specific subpackages.  What alternative platform identifier would you like me to switch on instead?

Or are you just saying you'd rather I unmarshal into a:

```go
type apiVersionWrapper struct {
  APIVersion `json:"apiVersion"`
}
```

instead of doing the [arbitrary-data decode dance][1]?  Or something else?

[1]: https://blog.golang.org/json-and-go#TOC_5.

File: pkg/asset/cluster/tfvars.go (hunk 2 above)
Comment (abhinavdahiya) [reply pkg/asset/cluster/tfvars.go]: > InstallConfig.Networking

this is more about k8s cluster networking than cloud networking. we might need separation inside that.. and keeping the fields in cloud specific allows us to not aggregate the name...

but i keeping the cloud networking cidr in Networking seems fine too.

> nodeCIDR 
no node has a meaning in k8s

File: pkg/asset/cluster/tfvars.go (hunk 4 above)
Comment (abhinavdahiya) [reply pkg/asset/cluster/tfvars.go]: we already do that for Machines, switch on platform and call platform specific TFVars. we don't need another asset.

File: pkg/tfvars/tfvars.go (hunk 7 above)
Comment (abhinavdahiya) [reply pkg/tfvars/tfvars.go]: if the machine is a type, then you can directly switch on `platform.(type)`

**Comment by wking** [comment]
Rebased onto master to resolve conflicts with 43284f7 -> 3230622.  Still a few FIXMEs to go, as well as rerolling the machine(set) assets to store structured data.

**Comment by wking** [comment]
I've pushed 3230622 -> 2be4578, fixing [gofmt][1] and [`masters slice cannot be empty`][2].

[1]: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/792/pull-ci-openshift-installer-master-gofmt/2185/build-log.txt
[2]: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/792/pull-ci-openshift-installer-master-e2e-aws/2902/build-log.txt

**Comment by wking** [comment]
CI is green :).  I'll circle back and get as many of the the remaining FIXMEs as I can (and the structured master-machine data) once I finish working up change-log entries since 0.9.0.

**Comment by jeremyeder** [comment]
Is this on hold for a particular reason?

**Comment by jatanmalde** [comment]
@wking When would this PR been merged. any ETA sir?

Adding the `instanceType` in `install-config` still does not works?

This PR would help allow changing the manifest before installation.Correct me if I am wrong.

Thanks.

**Comment by wking** [comment]
> When would this PR been merged. any ETA sir?

I'm working on rebasing it now.

> Adding the instanceType in install-config still does not works?

It's `type`, and I hear that that [*does* work now][1] (although #1076 wasn't part of 0.10.0, you'll need to wait for 0.11.0, any day now, to get that in a released installer).

> This PR would help allow changing the manifest before installation.

That's right, and it should only affect masters.  Changes to worker manifests should work today.

[1]: https://github.com/openshift/installer/issues/671#issuecomment-456192656

**Comment by wking** [comment]
I've pushed 70f3e02 -> 5ed2baa addressing the libvirt FIXME (although I haven't actually tested the resulting libvirt behavior yet).

**Comment by wking** [comment]
I've pushed 5ed2baa -> 49b6ff6 adding the OpenStack tunneling for region, external network and trunk support (I don't know what those mean, but I feel like they should be reflected in the OpenStack provider spec ;).  The push also rebases on top of #1154 to drop AWS IAM roles.  And 49b6ff6 is FIXME-free, so I've dropped the WIP prefix from the commit message and PR subjects :tada:

File: pkg/asset/cluster/tfvars.go (hunk 1 above)
Comment (wking) [reply pkg/asset/cluster/tfvars.go]: The master asset is typed with 2b2e8c149.

File: pkg/tfvars/aws/aws.go (hunk 5 above)
Comment (wking) [reply pkg/tfvars/aws/aws.go]: Consumes structured data in 2b2e8c149.

File: pkg/tfvars/libvirt/libvirt.go (hunk 6 above)
Comment (wking) [reply pkg/tfvars/libvirt/libvirt.go]: > should consume type not config bytes.

Consumes structured data in 2b2e8c149.

> vpcCidr is nt suitable in libvirt.

This was addressed by #983.

File: pkg/tfvars/tfvars.go (hunk 7 above)
Comment (wking) [reply pkg/tfvars/tfvars.go]: > if the machine is a type, then you can directly switch on `platform.(type)`

Done in 2b2e8c149e5.

File: pkg/asset/cluster/tfvars.go [hunk 8]
```diff
@@ -39,25 +40,55 @@ func (t *TerraformVariables) Dependencies() []asset.Asset {
...
 	}
 }
 
 // Generate generates the terraform.tfvars file.
 func (t *TerraformVariables) Generate(parents asset.Parents) error {
 	clusterID := &installconfig.ClusterID{}
 	installConfig := &installconfig.InstallConfig{}
-	bootstrap := &bootstrap.Bootstrap{}
-	master := &machine.Master{}
+	bootstrapIgnAsset := &bootstrap.Bootstrap{}
```
Comment (abhinavdahiya) [inline pkg/asset/cluster/tfvars.go]: the other variables arounf these don't add the `asset` suffix, so maybe just `bootstrapIgn` ?

File: pkg/asset/cluster/tfvars.go [hunk 9]
```diff
@@ -39,25 +40,55 @@ func (t *TerraformVariables) Dependencies() []asset.Asset {
...
-	parents.Get(clusterID, installConfig, bootstrap, master, rhcosImage)
+	parents.Get(clusterID, installConfig, bootstrapIgnAsset, masterIgnAsset, mastersAsset, rhcosImage)
 
-	bootstrapIgn := string(bootstrap.Files()[0].Data)
-	masterIgn := string(master.Files()[0].Data)
+	bootstrapIgn := string(bootstrapIgnAsset.Files()[0].Data)
+	masterIgn := string(masterIgnAsset.Files()[0].Data)
 
-	data, err := tfvars.TFVars(clusterID.ClusterID, installConfig.Config, string(*rhcosImage), bootstrapIgn, masterIgn)
+	var bridge string
```
Comment (abhinavdahiya) [inline pkg/asset/cluster/tfvars.go]: why not pass `installconfig.Platform` to TFVars ?

File: pkg/tfvars/tfvars.go [hunk 10]
```diff
@@ -21,80 +25,46 @@ type config struct {
...
+	*aws.AWS             `json:",inline"`
+	*libvirt.Libvirt     `json:",inline"`
+	*openstack.OpenStack `json:",inline"`
 }
 
-// TFVars converts the InstallConfig and Ignition content to
-// terraform.tfvar JSON.
-func TFVars(clusterID string, cfg *types.InstallConfig, osImage, bootstrapIgn, masterIgn string) ([]byte, error) {
+// TFVars generates terraform.tfvar JSON for launching the cluster.
+func TFVars(clusterID string, clusterName string, baseDomain string, machineCIDR *net.IPNet, bridge string, region string, externalNetwork string, trunkSupport string, osImage string, bootstrapIgn string, masterIgn string, masters []clusterapi.Machine) ([]byte, error) {
```
Comment (abhinavdahiya) [inline pkg/tfvars/tfvars.go]: This function has quite a few arguments. IMO we should replace some of these with `installconfig.Platform` or atleast document how each one is used.

File: pkg/tfvars/tfvars.go [hunk 11]
```diff
@@ -21,80 +25,46 @@ type config struct {
...
-				IfName: cfg.Platform.Libvirt.Network.IfName,
-			},
-			Image:     osImage,
-			MasterIPs: masterIPs,
-		}
-		if err := config.Libvirt.TFVars(&cfg.Networking.MachineCIDR.IPNet, config.Masters); err != nil {
-			return nil, errors.Wrap(err, "failed to insert libvirt variables")
+	var err error
+	machine := masters[0]
+	if awsConfig, ok := machine.Spec.ProviderSpec.Value.Object.(*awsprovider.AWSMachineProviderConfig); ok {
```
Comment (abhinavdahiya) [inline pkg/tfvars/tfvars.go]: can we use 
```go
switch provider := machine.Spec.ProviderSpec.Value.Object.(type) {
case *awsprovider.AWSMachineProviderConfig:
...
}
```

**Comment by abhinavdahiya** [comment]
this looks :100: 
2 things:

- thinking if https://github.com/openshift/installer/pull/792#discussion_r253168863 makes sense
- and one minor nit https://github.com/openshift/installer/pull/792#discussion_r253195528

I didn't see any drop in the defaults in terraform files, we didn't have any ?

File: pkg/asset/cluster/tfvars.go (hunk 8 above)
Comment (wking) [reply pkg/asset/cluster/tfvars.go]: > the other variables arounf these don't add the `asset` suffix, so maybe just `bootstrapIgn` ?

I was saving `bootstraIgn` for [here][1].

[1]: https://github.com/openshift/installer/pull/792/files#diff-bfad726be2a317f0c2bee99d4d62e23eR57

File: pkg/tfvars/tfvars.go (hunk 11 above)
Comment (wking) [reply pkg/tfvars/tfvars.go]: > can we use...

We could, but then we'd still need casts, wouldn't we?  Seems easier to combine the check with cast in an if/else chain.

**Comment by wking** [comment]
> I didn't see any drop in the defaults in terraform files, we didn't have any ?

I had a separate PR for that., but can squash it in here if you like.

**Comment by wking** [comment]
I'll reroll to make per-platform renderers for the per-platform variables.

File: pkg/tfvars/tfvars.go (hunk 11 above)
Comment (abhinavdahiya) [reply pkg/tfvars/tfvars.go]: Hmm... I don't think we need to cast... https://play.golang.org/p/uPq6ZlRtnpk

Comment (wking) [reply pkg/tfvars/tfvars.go]: > Hmm... I don't think we need to cast...

With:

```diff
diff --git a/pkg/tfvars/tfvars.go b/pkg/tfvars/tfvars.go
index 1c3c625..5e2cfd6 100644
--- a/pkg/tfvars/tfvars.go
+++ b/pkg/tfvars/tfvars.go
@@ -48,23 +48,25 @@ func TFVars(clusterID string, clusterName string, baseDomain string, machineCIDR
 
 	var err error
 	machine := masters[0]
-	if awsConfig, ok := machine.Spec.ProviderSpec.Value.Object.(*awsprovider.AWSMachineProviderConfig); ok {
-		config.AWS, err = aws.TFVars(awsConfig)
+	machineConfig := machine.Spec.ProviderSpec.Value.Object
+	switch machineConfig.(type) {
+	case *awsprovider.AWSMachineProviderConfig:
+		config.AWS, err = aws.TFVars(machineConfig)
 		if err != nil {
 			return nil, err
 		}
-	} else if libvirtConfig, ok := machine.Spec.ProviderSpec.Value.Object.(*libvirtprovider.LibvirtMachineProviderConfig); ok {
-		config.Libvirt, err = libvirt.TFVars(libvirtConfig, osImage, machineCIDR, bridge, config.Masters)
+	case *libvirtprovider.LibvirtMachineProviderConfig:
+		config.Libvirt, err = libvirt.TFVars(machineConfig, osImage, machineCIDR, bridge, config.Masters)
 		if err != nil {
 			return nil, err
 		}
-	} else if openStackConfig, ok := machine.Spec.ProviderSpec.Value.Object.(*openstackprovider.OpenstackProviderSpec); ok {
-		config.OpenStack, err = openstack.TFVars(openStackConfig, region, externalNetwork, trunkSupport)
+	case *openstackprovider.OpenstackProviderSpec:
+		config.OpenStack, err = openstack.TFVars(machineConfig, region, externalNetwork, trunkSupport)
 		if err != nil {
 			return nil, err
 		}
-	} else {
-		return nil, errors.Errorf("unrecognized master provider %#+v", machine.Spec.ProviderSpec.Value.Object)
+	default:
+		return nil, errors.Errorf("unrecognized master provider %#+v", machineConfig)
 	}
 
 	return json.MarshalIndent(config, "", "  ")
```

on top of 9d94e4204f40, I get:

```console
$ hack/build.sh
...
pkg/tfvars/tfvars.go:54:31: cannot use machineConfig (type runtime.Object) as type *"github.com/openshift/installer/vendor/sigs.k8s.io/cluster-api-provider-aws/pkg/apis/awsproviderconfig/v1alpha1".AWSMachineProviderConfig in argument to aws.TFVars: need type assertion
pkg/tfvars/tfvars.go:59:39: cannot use machineConfig (type runtime.Object) as type *"github.com/openshift/installer/vendor/github.com/openshift/cluster-api-provider-libvirt/pkg/apis/libvirtproviderconfig/v1alpha1".LibvirtMachineProviderConfig in argument to libvirt.TFVars: need type assertion
pkg/tfvars/tfvars.go:64:43: cannot use machineConfig (type runtime.Object) as type *"github.com/openshift/installer/vendor/sigs.k8s.io/cluster-api-provider-openstack/pkg/apis/openstackproviderconfig/v1alpha1".OpenstackProviderSpec in argument to openstack.TFVars: need type assertion
```

Am I just doing it wrong?

**Comment by wking** [comment]
The tests that we require are green, [libvirt got through cluster-creation successfully][1], and [OpenStack][1] died with:

```
level=fatal msg="failed to fetch Terraform Variables: failed to load asset \"Install Config\": invalid \"install-config.yaml\" file: [platform.openstack.region: Unsupported value: \"RegionOne\": supported values: \"regionOne\", platform.openstack.computeFlavor: Unsupported value: \"\": supported values: \"m1.large\", \"m1.large2\", \"m1.tiny\", \"m1.small\", \"m1.medium\", \"m1.xlarge\"]"
```

which I suspect is a mismatch between the release repo's supplied `install-config.yaml` and the OpenStack implementation referenced by the CI credentials.

[1]: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/792/pull-ci-openshift-installer-master-e2e-libvirt/296/build-log.txt
[2]: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/792/pull-ci-openshift-installer-master-e2e-openstack/24/build-log.txt

File: pkg/tfvars/tfvars.go (hunk 11 above)
Comment (staebler) [reply pkg/tfvars/tfvars.go]: @wking You were missing the part where you store the result of `machineConfig.(type)` and use that value, which will have already been cast to the specific type.

File: pkg/asset/cluster/tfvars.go [hunk 12]
```diff
@@ -1,27 +1,47 @@
...
+	TfPlatformVarsFileName = "terraform.%s.auto.tfvars"
+
 	tfvarsAssetName = "Terraform Variables"
 )
 
 // TerraformVariables depends on InstallConfig and
 // Ignition to generate the terrafor.tfvars.
 type TerraformVariables struct {
-	File *asset.File
+	files []*asset.File
```
Comment (abhinavdahiya) [inline pkg/asset/cluster/tfvars.go]: cc @staebler

File: pkg/asset/cluster/tfvars.go (hunk 8 above)
Comment (abhinavdahiya) [reply pkg/asset/cluster/tfvars.go]: looks like `boostrapIgn` is only used once [here](https://github.com/openshift/installer/pull/792/commits/c1c86862ff109bde9062bae135684238750432da#diff-bfad726be2a317f0c2bee99d4d62e23eR84)

why create a new variable for one time use....

File: pkg/asset/cluster/tfvars.go [hunk 13]
```diff
@@ -39,39 +59,99 @@ func (t *TerraformVariables) Dependencies() []asset.Asset {
...
+			Data:     data,
+		},
+	}
+
+	if len(mastersAsset.Machines) == 0 {
+		return errors.Errorf("master slice cannot be empty")
+	}
+
+	platform := installConfig.Config.Platform.Name()
+	switch platform {
```
Comment (abhinavdahiya) [inline pkg/asset/cluster/tfvars.go]: nit: `switch platform := installConfig.Config.Platform.Name() {`

File: pkg/asset/machines/master.go [hunk 14]
```diff
@@ -82,53 +79,31 @@ func (m *Master) Generate(dependencies asset.Parents) error {
...
 		mpool.Set(ic.Platform.OpenStack.DefaultMachinePlatform)
 		mpool.Set(pool.Platform.OpenStack)
 		pool.Platform.OpenStack = &mpool
 
-		machines, err := openstack.Machines(clusterID.ClusterID, ic, &pool, string(*rhcosImage), "master", "master-user-data")
+		m.Machines, err = openstack.Machines(clusterID.ClusterID, ic, &pool, string(*rhcosImage), "master", "master-user-data")
 		if err != nil {
 			return errors.Wrap(err, "failed to create master machine objects")
 		}
-		openstack.ConfigMasters(machines, ic.ObjectMeta.Name)
```
Comment (abhinavdahiya) [inline pkg/asset/machines/master.go]: do we want to replace this?

File: pkg/asset/cluster/tfvars.go (hunk 12 above)
Comment (staebler) [reply pkg/asset/cluster/tfvars.go]: This needs to be a public field for consistency between loading from on-disk files and loading from the asset-store state file.

File: pkg/asset/cluster/tfvars.go (hunk 8 above)
Comment (wking) [reply pkg/asset/cluster/tfvars.go]: > looks like boostrapIgn is only used once here
>
> why create a new variable for one time use....

Because [that's what we do in master][1]?  But if you don't like our current local variables, I can remove the single-use ones in this PR.  If you want that, did you just want me to clean them out of this function?

[1]: https://github.com/openshift/installer/blob/da6d45b36c8b39e40fe28a31e53337405e28162d/pkg/asset/cluster/tfvars.go#L54

File: pkg/tfvars/aws/aws.go [hunk 15]
```diff
@@ -1,22 +1,48 @@
...
+	"sigs.k8s.io/cluster-api-provider-aws/pkg/apis/awsproviderconfig/v1alpha1"
+)
+
+type config struct {
 	EC2AMIOverride string            `json:"aws_ec2_ami_override,omitempty"`
 	ExtraTags      map[string]string `json:"aws_extra_tags,omitempty"`
-	Master         `json:",inline"`
-	Region         string `json:"aws_region,omitempty"`
+	EC2Type        string            `json:"aws_master_ec2_type,omitempty"`
+	IOPS           *int64            `json:"aws_master_root_volume_iops,omitempty"`
```
[the remark this answers is not in the document]
Comment (wking) [reply pkg/tfvars/aws/aws.go]: > Why this change from c1c8686#diff-97b797a6f81e933f2ab014e338af0ed9L19

So I could do a direct assignment [here][1] without having to worry about `nil`-ness.

[1]: https://github.com/openshift/installer/commit/c1c86862ff109bde9062bae135684238750432da#diff-97b797a6f81e933f2ab014e338af0ed9R42

File: pkg/asset/machines/master.go (hunk 14 above)
Comment (wking) [reply pkg/asset/machines/master.go]: > do we want to replace this?

It's [currently a no-op in master][1], but sure, done in c1c8686 -> e5707ed.

[1]: https://github.com/openshift/installer/blob/da6d45b36c8b39e40fe28a31e53337405e28162d/pkg/asset/machines/openstack/machines.go#L109-L114

File: pkg/asset/cluster/tfvars.go (hunk 13 above)
Comment (wking) [reply pkg/asset/cluster/tfvars.go]: Fixed with c1c8686 -> e5707ed.

File: pkg/tfvars/aws/aws.go (hunk 15 above)
[the remark this answers is not in the document]
Comment (staebler) [reply pkg/tfvars/aws/aws.go]: We want to get rid of the defaults in the terraform variables, though (https://github.com/openshift/installer/pull/1128). So we do want the iops, size, and type variables to not be pointers and not have `omitempty`.

File: pkg/asset/cluster/tfvars.go (hunk 12 above)
Comment (wking) [reply pkg/asset/cluster/tfvars.go]: > This needs to be a public field...

Fixed with c1c8686 -> e5707ed.

**Comment by wking** [comment]
I've pushed c1c8686 -> e5707ed, rebasing onto master and addressing the most recent round of review (with the possible exception of [this][1], where I'm waiting on feedback from @abhinavdahiya).

[1]: https://github.com/openshift/installer/pull/792#discussion_r253609948

**Comment by wking** [comment]
I've pushed e5707ed -> 2d72c95, fixing two compilation errors.

File: pkg/destroy/bootstrap/bootstrap.go [hunk 16]
```diff
@@ -43,21 +46,31 @@ func Destroy(dir string) (err error) {
...
 	defer os.RemoveAll(tempDir)
 
+	extraArgs := []string{}
 	for _, filename := range copyNames {
-		err = copy(filepath.Join(dir, filename), filepath.Join(tempDir, filename))
+		sourcePath := filepath.Join(dir, filename)
+		targetPath := filepath.Join(tempDir, filename)
+		err = copy(sourcePath, targetPath)
 		if err != nil {
+			if os.IsNotExist(err) && err.(*os.PathError).Path == sourcePath && filename == tfPlatformVarsFileName {
```
Comment (abhinavdahiya) [inline pkg/destroy/bootstrap/bootstrap.go]: Hmm, i think we need it for all the current platforms, currently right?

File: pkg/tfvars/aws/aws.go [hunk 17]
```diff
@@ -1,22 +1,63 @@
...
+		return nil, errors.New("block device slice cannot be empty")
+	}
+
+	rootVolume := masterConfig.BlockDevices[0]
+	if rootVolume.EBS == nil {
+		return nil, errors.New("EBS information must be configured for the root volume")
+	}
+
+	if rootVolume.EBS.Iops == nil {
+		cfg.IOPS = 400
```
Comment (abhinavdahiya) [inline pkg/tfvars/aws/aws.go]: i don't think these defaults must exist in this package...

Comment (wking) [reply pkg/tfvars/aws/aws.go]: > i don't think these defaults must exist in this package...

Did you want me to just assume they were set and panic if they aren't?

File: pkg/destroy/bootstrap/bootstrap.go (hunk 16 above)
Comment (wking) [reply pkg/destroy/bootstrap/bootstrap.go]: > Hmm, i think we need it for all the current platforms, currently right?

`none` doesn't need it, although it's unlikely to end up in `destroy bootstrap`.  And per [this][1] (in flight, and for operators, but seems like a useful generic principle), we want to treat unrecognized platforms like `none` in most places.

[1]: https://github.com/openshift/installer/pull/1112/files#diff-6532666297c6115f7774f93ebab396c4R156

**Comment by wking** [comment]
Oh rats.  I just realized that one drawback to consuming `Master.Machines` is that that asset is not loadable.  As it stands, this PR will fix the "Go defaults applied to `Master.Machines` do not affect Terraform" issue (which is good), but it will not fix the "I ran `create manifests` and edited `openshift/99_openshift-cluster-api_master-machines.yaml` because *that* is loaded back in downstream of the `Master` asset.  Do we want to land this as it stands and address that later, or should I go back to the "parse from YAML" approach I had earlier and pull these out of the `Openshift` asset, @abhinavdahiya?

**Comment by abhinavdahiya** [comment]
> Oh rats. I just realized that one drawback to consuming `Master.Machines` is that that asset is not loadable. As it stands, this PR will fix the "Go defaults applied to `Master.Machines` do not affect Terraform" issue (which is good), but it will not fix the "I ran `create manifests` and edited `openshift/99_openshift-cluster-api_master-machines.yaml`" because _that_ is loaded back in downstream of the `Master` asset. Do we want to land this as it stands and address that later, or should I go back to the "parse from YAML" approach I had earlier and pull these out of the `Openshift` asset, @abhinavdahiya?

Hmmm, so maybe lets do the merge as-is for `Go defaults applied to `Master.Machines` do not affect Terraform issue` and fix the `I ran `create manifests and edited openshift/99_openshift-cluster-api_master-machines.yaml` issue later on... :(

**Comment by wking** [comment]
Prow thinks [tf-lint is still running][1].

/retest

[1]: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_installer/792/pull-ci-openshift-installer-tf-lint/2921

File: pkg/destroy/bootstrap/bootstrap.go (hunk 16 above)
Comment (abhinavdahiya) [reply pkg/destroy/bootstrap/bootstrap.go]: can you include that in commit message or comment in code.

File: pkg/tfvars/aws/aws.go (hunk 17 above)
Comment (abhinavdahiya) [reply pkg/tfvars/aws/aws.go]: expect them to be set and error otherwise, maybe ?

Comment (wking) [reply pkg/tfvars/aws/aws.go]: > expect them to be set and error otherwise, maybe ?

Done with 42a8a10 -> 6d449c5.

File: pkg/destroy/bootstrap/bootstrap.go (hunk 16 above)
Comment (wking) [reply pkg/destroy/bootstrap/bootstrap.go]: > can you include that in commit message or comment in code.

Added commit-message discussion in 42a8a10 -> 6d449c5.

**Comment by wking** [comment]
Rebased around #1175 with 6d449c5 -> 3326b6b.  I'm looking forward to being able to drop `MastersDeprecated`.  @abhinavdahiya, can you take another look?

**Comment by wking** [comment]
[e2e-aws][1]:

```

Flaky tests:

[Conformance][Area:Networking][Feature:Router] The HAProxy router should serve the correct routes when scoped to a single namespace and label set [Suite:openshift/conformance/parallel/minimal]

Failing tests:

[Conformance][Area:Networking][Feature:Router] The HAProxy router should serve routes that were created from an ingress [Suite:openshift/conformance/parallel/minimal]
```

/retest

[1]: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_installer/792/pull-ci-openshift-installer-master-e2e-aws/3496
