### PR TITLE
Bug 1710981: Default AWS instance type to 'm5'

### LINKED ISSUE #2919: aws: Use modern instance types by default
OK so I went down a bit of a rabbit hole because @sinnykumari hit a bug where trying to use `kernel-rt` in AWS via the MCO caused the instance to apparently not have networking on startup.

The real bug here is that the installer is defaulting to old "m4" instance types.  AWS now has "m5" instance types which have [enhanced networking](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking-ena.html) among other things.  And notably, `kernel-rt` does include the `ena` driver, but apparently not the `xen_netfront` one used for older types.

There's a lot of history and related PRs here, among them:

- https://github.com/openshift/installer/pull/1163
- https://github.com/openshift/installer/pull/1087

And https://github.com/openshift/installer/commit/06e58e0881cefb78e7a0cf8976d773a96d8a3ee9 is highly relevant.

Looking at e.g. `us-east-2` (Ohio), it's actually *cheaper* to use `m5.xlarge` versus `m4.xlarge`:

```
m5.xlarge | 4 | 16 | 16 GiB | EBS Only | $0.192 per Hour
-- | -- | -- | -- | -- | --

m4.xlarge | 4 | 13 | 16 GiB | EBS Only | $0.20 per Hour
-- | -- | -- | -- | -- | --
```

### PR DESCRIPTION
**Pull request by mtnbikenc**
Changes default AWS instance type from m4 to m5.

Fixes #2919.

### CODE REVIEW

File: pkg/types/aws/defaults/platform.go [hunk 1]
```diff
@@ -6,13 +6,13 @@ import (
...
 var (
 	defaultMachineClass = map[string][]string{
-		"ap-east-1":      {"m5", "m4"},
-		"ap-northeast-2": {"m5", "m4"},
-		"eu-north-1":     {"m5", "m4"},
-		"eu-west-3":      {"m5", "m4"},
-		"me-south-1":     {"m5", "m4"},
-		"us-gov-east-1":  {"m5", "m4"},
-		"us-west-2":      {"m5", "m4"},
+		// "ap-east-1":      {"m5", "m4"},
```
Comment (mtnbikenc) [inline pkg/types/aws/defaults/platform.go:9]: @abhinavdahiya Should we just rip out all the logic for having different defaults for different regions or keep the logic and structure in case we need to implement something similar in the future?

Comment (abhinavdahiya) [reply pkg/types/aws/defaults/platform.go:9]: i think we should remove the overrides, but keep the mechanism in place.

Comment (wking) [reply pkg/types/aws/defaults/platform.go:9]: we need to keep some overrides for regions/zones that lack m5 support, right?

Comment (wking) [reply pkg/types/aws/defaults/platform.go:9]: never mind, I'm stale after the removal of `platformtests/` (which I've just filed #3856 to wrap up).  I'm not clear on why we would need/want the ability to set overrides if we trust the dynamic APIs we've used since #3051.
