### PR TITLE
destroy: delete snapshots used in ami copies

### LINKED ISSUE #1342: Uninstall leaking snapshot that backs the AMI
# Version

```console
$ openshift-install version
./bin/openshift-install unreleased-master-457-g9596c7ffa001989c5453d8aff334f464b05c7a4d
```

# Platform (aws|libvirt|openstack):
aws

# What happened?

After uninstalling/destroying a cluster, the snapshot that backs the AMI that gets created during installation is left hanging around.

# What you expected to happen?

Clean up the snapshot that backs the AMI as part of deleting the AMI.

# How to reproduce it (as minimally and precisely as possible)?

```console
# install a cluster

# get the snapshot backing the newly created AMI
$ aws ec2 describe-images --filters "Name=tag:kubernetes.io/cluster/jdiaz-master-2nqdz,Values=owned" --region us-east-1 | jq -r .Images[].BlockDeviceMappings[].Ebs.SnapshotId
snap-0e75eb72357f405d9

$ ./openshift-install destroy cluster

# the snapshot is still around after destroy is complete
$ aws ec2 describe-snapshots --snapshot-ids snap-0e75eb72357f405d9 --region us-east-1  | jq -r .Snapshots[].SnapshotId
snap-0e75eb72357f405d9
```

# Anything else we need to know?

The snapshot isn't tagged (which probably explains why it isn't getting cleaned up).

```
$ aws ec2 describe-tags --filters "Name=resource-id,Values=snap-0e75eb72357f405d9" --region us-east-1
{
    "Tags": []
}
```

# References

### PR DESCRIPTION
**Pull request by staebler**
When the encrypted AMI used by the cluster is created, a snapshot is created as well. This snapshot needs to be explicitly deleted when the cluster is destroyed to avoid leaking resources. Unfortunately,
the snapshot does not have any tags when it is created. The snapshot can be found from the AMI's block device mappings, though. When the destroyer finds an AMI to delete, the destroyer will tag the snapshots used by the AMI with tags that match the filter used to find the AMI. This will allow the destroyer to find the snapshots on subsequent queries using that filter.

It would be preferably if the snapshot were tagged during the cluster creation. There is no way that I see to tag the snapshot when the AMI is created, using the terraform aws provider. There may be a way to have terraform assume ownership of the snapshot after the AMI is created and modify the tags of the snapshot after that. Or there may be a way to run some shell code from within terraform to modify the tags (although that would necessitate having the AWS CLI installed, which I think is a non-starter). In any event, those are things that could be looked into as a follow-on. But for now, the destroyer needs to stop leaking the snapshots, and these changes accomplish that.

Fixes #1342

### CODE REVIEW

**Comment by wking** [comment]
> There may be a way to have terraform assume ownership of the snapshot after the AMI is created and modify the tags of the snapshot after that.

You [can get the snapshot ID after the copy][1], but we currently can't tag the snapshot.  There's some upstream discussion about supporting this sort of thing in the future: terraform-providers/terraform-provider-aws#3143, hashicorp/terraform#17352, but this is unlikely to be a short-term possibility.

[1]: https://www.terraform.io/docs/providers/aws/r/ami_copy.html#attributes-reference

File: pkg/destroy/aws/aws.go [hunk 1]
```diff
@@ -504,6 +525,65 @@ func deleteEC2Image(client *ec2.EC2, id string, logger logrus.FieldLogger) error
...
+
+func deleteEC2Snapshots(client *ec2.EC2, snapshots []string, logger logrus.FieldLogger) error {
+	failedSnapshotsCh := make(chan string, len(snapshots))
+
+	var wg sync.WaitGroup
+	wg.Add(len(snapshots))
+	for i, id := range snapshots {
+		go func(ix int, snapshotId string) {
+			defer wg.Done()
+			// make at most 10 attempts over around 5 minutes
```
Comment (wking) [inline pkg/destroy/aws/aws.go]: I think we want to run forever, until someone kills us (I'm also ok adding a `Context` argument for Go consumers who want to gently cancel).

File: pkg/destroy/aws/aws.go [hunk 2]
```diff
@@ -504,6 +525,65 @@ func deleteEC2Image(client *ec2.EC2, id string, logger logrus.FieldLogger) error
 		return err
 	}
 
+	logger.Info("Deleted")
+
+	// need to delete the snapshots after deleting the ami. aws will block the
+	// snapshot deletion with an InvalidSnapshot.InUse error until the ami is deleted.
+	return deleteEC2Snapshots(client, snapshots, logger)
```
Comment (wking) [inline pkg/destroy/aws/aws.go]: Instead of looping over snapshots inside `deleteEC2Image`, how about we actively tag the AMI's snapshots before deleting the AMI?  Then we can deregister the AMI and exit `deleteEC2Image`.  The snapshots will get picked up by future loops of the tag-lister.  That also protects us from leaking if somebody kills the teardown code after the AMI is removed but before the snapshots are gone, because a new teardown attempt with the same parameters would still pick up the snapshots by tag.

File: pkg/destroy/aws/aws.go [hunk 3]
```diff
@@ -504,6 +525,65 @@ func deleteEC2Image(client *ec2.EC2, id string, logger logrus.FieldLogger) error
...
+
+func deleteEC2Snapshot(client *ec2.EC2, id string, logger logrus.FieldLogger) error {
+	_, err := client.DeleteSnapshot(&ec2.DeleteSnapshotInput{
+		SnapshotId: &id,
+	})
+	if err != nil {
+		if err.(awserr.Error).Code() == "InvalidSnapshotID.NotFound" {
+			return nil
+		}
+		logger.Debugf("error deleting snapshot: %v", err)
```
Comment (wking) [inline pkg/destroy/aws/aws.go]: We're returning the `err`, so the caller can log about it if they want.  I think we want to drop this line here.

File: pkg/destroy/aws/aws.go [hunk 4]
```diff
@@ -504,6 +525,65 @@ func deleteEC2Image(client *ec2.EC2, id string, logger logrus.FieldLogger) error
...
+		failedSnapshots = append(failedSnapshots, id)
+	}
+	if len(failedSnapshots) > 0 {
+		return errors.Errorf("failed to delete snapshots %s", strings.Join(failedSnapshots, ", "))
+	}
+
+	return nil
+}
+
+func deleteEC2Snapshot(client *ec2.EC2, id string, logger logrus.FieldLogger) error {
```
Comment (wking) [inline pkg/destroy/aws/aws.go]: `deleteEC2Snapshot` alphabetizes between `deleteEC2SecurityGroup` and `deleteEC2Subnet`, so this function definition should be shifted down there.

**Comment by wking** [comment]
You can [tag snapshots on creation since 2018-04-02][1], so there may be something we can do about supporting tagged snapshots in the AMI copy at some point.

[1]: https://aws.amazon.com/blogs/compute/tag-amazon-ebs-snapshots-on-creation-and-implement-stronger-security-policies/

File: pkg/destroy/aws/aws.go (hunk 2 above)
Comment (wking) [reply pkg/destroy/aws/aws.go]: > Instead of looping over snapshots inside deleteEC2Image, how about we actively tag the AMI's snapshots before deleting the AMI?

I've pushed two fixup commits with this approach, although I haven't had time to test them yet.  Pull with:

```console
$ git pull git://github.com/wking/openshift-installer snapshot-fixups
```

and squash 81d967c6c if it looks good (there's also a drive-by `Wrapf` -> `Wrap` fixup, which you can take or leave).  The diff is fairly noisy from plumbing `filter` through.  I plumbed it through the whole chain for consistency, but if you want a smaller diff you could just plumb it through `deleteARN` -> `deleteEC2` -> `deleteEC2Image` (which you can get from my branch by squashing in eadbf6bc9 as well).

File: pkg/destroy/aws/aws.go (hunk 1 above)
Comment (staebler) [reply pkg/destroy/aws/aws.go]: Running forever has the worst-case scenario of blocking the destroy of all of the other resources. But I guess that then the user can run destroy again to clean up the other resources since the subsequent destroys will not attempt to delete the snapshots as they won't be found. I prefer the proposal of tagging the snapshot during destroy over running forever, however.

Comment (staebler) [reply pkg/destroy/aws/aws.go]: Obsolete by c07b1ed to fcade11.

File: pkg/destroy/aws/aws.go (hunk 2 above)
Comment (staebler) [reply pkg/destroy/aws/aws.go]: Done in c07b1ed to fcade11.

File: pkg/destroy/aws/aws.go (hunk 3 above)
Comment (staebler) [reply pkg/destroy/aws/aws.go]: Obsolete by c07b1ed to fcade11.

File: pkg/destroy/aws/aws.go (hunk 4 above)
Comment (staebler) [reply pkg/destroy/aws/aws.go]: Done in c07b1ed to fcade11.

**Comment by wking** [comment]
/lgtm
/hold

We can pull the hold once we see snapshot removal in the CI logs.

**Comment by wking** [comment]
[e2e-aws][1]:

```
time="2019-03-01T15:21:09Z" level=info msg=Deleted arn="arn:aws:ec2:us-east-1
:460538899914:snapshot/snap-029a72073c68c9f72" id=snap-029a72073c68c9f72
```

/hold cancel

[1]: https://storage.googleapis.com/origin-ci-test
/pr-logs/pull/openshift_installer/1346/pull-ci-openshift-installer-master-e2e
-aws/4324/artifacts/e2e-aws/installer/.openshift_install.log
