### PR TITLE
pkg/asset/machines: Convert Master to a WriteableAsset

### LINKED ISSUE #1205: create manifests then create cluster panic
# Version

```console
$ openshift-install version
openshift-install unreleased-master-246-g193a3f2cb7b8da375da90126ac4757254cdb17fe
```

# Platform (aws|libvirt|openstack):
libvirt

# What happened?

* Installer compiled with libvirt support
* install-config.yaml content:
```
apiVersion: v1beta1
baseDomain: ocp4.lan
machines:
- name: master
  platform: {}
  replicas: 1
- name: worker
  platform: {}
  replicas: 1
metadata:
  creationTimestamp: null
  name: minwi
networking:
  clusterNetworks:
  - cidr: 10.128.0.0/14
    hostSubnetLength: 9
  machineCIDR: 192.168.126.0/24
  serviceCIDR: 172.30.0.0/16
  type: OpenshiftSDN
platform:
  libvirt:
    URI: qemu+tcp://192.168.122.1/system
    network:
      if: tt0
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"x","email":"x"},"quay.io":{"auth":"x","email":"x"}}}'
sshKey: |
  ssh-rsa x x@x.com
```
* `mkdir assets`
* `cp install-config.yaml assets/`
* `openshift-install create manifests --dir=./assets/ --log-level=debug`
* Manifests generated:
```
assets/
assets/.openshift_install.log
assets/.openshift_install_state.json
assets/manifests
assets/manifests/04-openshift-machine-config-operator.yaml
assets/manifests/09-openshift-service-signer-namespace.yaml
assets/manifests/cluster-config.yaml
assets/manifests/cluster-dns-01-crd.yaml
assets/manifests/cluster-dns-02-config.yml
assets/manifests/cluster-infrastructure-01-crd.yaml
assets/manifests/cluster-infrastructure-02-config.yml
assets/manifests/cluster-ingress-01-crd.yaml
assets/manifests/cluster-ingress-02-config.yml
assets/manifests/cluster-network-01-crd.yml
assets/manifests/cluster-network-02-config.yml
assets/manifests/cvo-overrides.yaml
assets/manifests/etcd-service.yaml
assets/manifests/host-etcd-service-endpoints.yaml
assets/manifests/host-etcd-service.yaml
assets/manifests/kube-cloud-config.yaml
assets/manifests/kube-system-configmap-etcd-serving-ca.yaml
assets/manifests/kube-system-configmap-root-ca.yaml
assets/manifests/kube-system-secret-etcd-client.yaml
assets/manifests/machine-config-server-tls-secret.yaml
assets/manifests/openshift-service-signer-secret.yaml
assets/manifests/pull.json
assets/openshift
assets/openshift/99_binding-discovery.yaml
assets/openshift/99_kubeadmin-password-secret.yaml
assets/openshift/99_openshift-cluster-api_cluster.yaml
assets/openshift/99_openshift-cluster-api_master-machines.yaml
assets/openshift/99_openshift-cluster-api_master-user-data-secret.yaml
assets/openshift/99_openshift-cluster-api_worker-machineset.yaml
assets/openshift/99_openshift-cluster-api_worker-user-data-secret.yaml
```
* `openshift-install create cluster --dir=./assets/ --log-level=debug`
Fails with:

```
DEBUG   Fetching "Master Ignition Config"...       
DEBUG   Reusing previously-fetched "Master Ignition Config" 
DEBUG   Fetching "Master Machines"...              
DEBUG   Reusing previously-fetched "Master Machines" 
DEBUG Generating "Terraform Variables"...          
panic: interface conversion: runtime.Object is nil, not *v1alpha1.LibvirtMachineProviderConfig

goroutine 1 [running]:
github.com/openshift/installer/pkg/asset/cluster.(*TerraformVariables).Generate(0x8acca90, 0xc420b8b0e0, 0xc420ec79f0, 0x2)
	/home/edu/go/src/github.com/openshift/installer/pkg/asset/cluster/tfvars.go:120 +0x136f
github.com/openshift/installer/pkg/asset/store.(*storeImpl).fetch(0xc420a20e40, 0x53717a0, 0x8acca90, 0x0, 0x0, 0x46633a0, 0x47b48a0)
	/home/edu/go/src/github.com/openshift/installer/pkg/asset/store/store.go:226 +0x7c0
github.com/openshift/installer/pkg/asset/store.(*storeImpl).Fetch(0xc420a20e40, 0x53717a0, 0x8acca90, 0x53717a0, 0x8acca90)
	/home/edu/go/src/github.com/openshift/installer/pkg/asset/store/store.go:76 +0x4b
main.runTargetCmd.func1(0x7fff94670566, 0x9, 0xc420a81f00, 0xc42049fbf8)
	/home/edu/go/src/github.com/openshift/installer/cmd/openshift-install/create.go:157 +0x13f
main.runTargetCmd.func2(0x8986700, 0xc420a81da0, 0x0, 0x2)
	/home/edu/go/src/github.com/openshift/installer/cmd/openshift-install/create.go:182 +0x81
github.com/openshift/installer/vendor/github.com/spf13/cobra.(*Command).execute(0x8986700, 0xc420a81d60, 0x2, 0x2, 0x8986700, 0xc420a81d60)
	/home/edu/go/src/github.com/openshift/installer/vendor/github.com/spf13/cobra/command.go:766 +0x2c1
github.com/openshift/installer/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420a34780, 0x0, 0xc420a35900, 0xc420a348d0)
	/home/edu/go/src/github.com/openshift/installer/vendor/github.com/spf13/cobra/command.go:852 +0x30a
github.com/openshift/installer/vendor/github.com/spf13/cobra.(*Command).Execute(0xc420a34780, 0xc42049feb8, 0x1)
	/home/edu/go/src/github.com/openshift/installer/vendor/github.com/spf13/cobra/command.go:800 +0x2b
main.installerMain()
	/home/edu/go/src/github.com/openshift/installer/cmd/openshift-install/main.go:56 +0x132
main.main()
	/home/edu/go/src/github.com/openshift/installer/cmd/openshift-install/main.go:40 +0x9b
```

# What you expected to happen?

Create a proper OCP4 cluster on libvirt.

# How to reproduce it (as minimally and precisely as possible)?

See before

# Anything else we need to know?

Running only `create cluster` works:

* Installer compiled with libvirt support
* install-config.yaml content:
```
apiVersion: v1beta1
baseDomain: ocp4.lan
machines:
- name: master
  platform: {}
  replicas: 1
- name: worker
  platform: {}
  replicas: 1
metadata:
  creationTimestamp: null
  name: minwi
networking:
  clusterNetworks:
  - cidr: 10.128.0.0/14
    hostSubnetLength: 9
  machineCIDR: 192.168.126.0/24
  serviceCIDR: 172.30.0.0/16
  type: OpenshiftSDN
platform:
  libvirt:
    URI: qemu+tcp://192.168.122.1/system
    network:
      if: tt0
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"x","email":"x"},"quay.io":{"auth":"x","email":"x"}}}'
sshKey: |
  ssh-rsa x x@x.com
```
* `mkdir assets`
* `cp install-config.yaml assets/`
* `openshift-install create cluster --dir=./assets/ --log-level=debug`

```
...
DEBUG                                              
DEBUG State path: /tmp/openshift-install-168351161/terraform.tfstate 
INFO Waiting up to 30m0s for the Kubernetes API... 
...
```

# References

### PR DESCRIPTION
**Pull request by wking**
Since 3326b6b3 (#792), we've been consuming structured master configurations to generate Terraform variables.  But before this commit, the `Openshift` asset was the `WriteableAsset` responsible for the master configs, giving you the following issue:

1. `openshift-install create manifests`
    1. `Master` asset populated with structured data
    2. `Openshift` asset pulls in `Master`, flattens to YAML, and writes to disk.

2. `openshift-install create cluster`
    1. `Openshift` asset reads master YAML from disk.
    2. `TerraformVariables` asset pulls in `Master`, but it's empty.
    3. Panic (#1205).

With this commit, responsibility for reading and writing master manifests to disk gets shifted to the `Master` asset itself.

Unpacking the YAML data into the appropriate structures is a bit hairy.  I'm not familiar with this code though, maybe there's a better way.  It will help once we complete the shift to the OpenShift machine-API types started in cf60daa1 (#1175).

I've also taken the opportunity to drop the list.  It saves us a few lines of code for (de)serializing, and there's no upside to collecting the `Machine` configs together in a single file.

The "glob, but not the master files" logic in the `Openshift` loader is also a bit ugly.  Moving forward, I expect us to push the remaining `Openshift` assets out into their own assets as well, which would allow us to tighten down on the wildcard there.

@staebler, can you check the asset logic here?  I _think_ I have it right, but I'm doing more pattern-matching than understanding ;).

Fixes #1205

### CODE REVIEW

**Comment by dgoodwin** [comment]
Is there anywhere in the code you could slip in a unit test that covered the installconfig on disk use case without requiring an actual provision?

**Comment by wking** [comment]
> Is there anywhere in the code you could slip in a unit test that covered the installconfig on disk use case without requiring an actual provision?

#552 has a framework for something like that, although the issue here is manifests on disk, not install-config on disk.

**Comment by wking** [comment]
I've pushed 7aaa902 -> 7f61d57 to fix the golint issue.  I'm not sure how to handle [the unit error][1]:

```
--- FAIL: TestCreatedAssetsAreNotDirty (10.29s)
    --- FAIL: TestCreatedAssetsAreNotDirty/manifests (2.99s)
    	assetcreate_test.go:108: 
    			Error Trace:	assetcreate_test.go:108
    			Error:      	Not equal: 
    			            	expected: &machines.Master{Machines:[]v1beta1.Machine{}, MachinesDeprecated:[]v1alpha1.Machine(nil), FileList:[]*asset.File{(*asset.File)(0xc4207303f0)}}
    			            	actual  : &machines.Master{Machines:[]v1beta1.Machine(nil), MachinesDeprecated:[]v1alpha1.Machine(nil), FileList:[]*asset.File{(*asset.File)(0xc420b292c0)}}
    			            	
    			            	Diff:
    			            	--- Expected
    			            	+++ Actual
    			            	@@ -1,4 +1,3 @@
    			            	 (*machines.Master)({
    			            	- Machines: ([]v1beta1.Machine) {
    			            	- },
    			            	+ Machines: ([]v1beta1.Machine) <nil>,
    			            	  MachinesDeprecated: ([]v1alpha1.Machine) <nil>,
    			Test:       	TestCreatedAssetsAreNotDirty/manifests
    			Messages:   	fetched and generated asset "Master Machines" are not equal
```

More on that issue [here][2], but I'm currently distinguishing between "set to the empty list" and "unset" when consuming the data while we have both `Machines` and `MachinesDeprecated`.  Maybe I have to give up on that and switch to `len(master.Machines)` instead, unless @staebler has a way to coerce to `nil` on load?

[1]: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/1211/pull-ci-openshift-installer-master-unit/2606/build-log.txt
[2]: https://github.com/openshift/installer/commit/75ab106010295abdd0e79e1f39a010d03b1b8e3e#diff-66b4febb36af0238bb6c09e72c1c44ecR114

**Comment by staebler** [comment]
> unless @staebler has a way to coerce to `nil` on load?

I don't have a better solution for you. I had the same problem.

https://github.com/openshift/installer/blob/ad65a3a936691635b1d550e949d72b93da412075/pkg/asset/machines/master.go#L99-L102

File: pkg/asset/machines/master.go [hunk 1]
```diff
@@ -114,9 +135,108 @@ func (m *Master) Generate(dependencies asset.Parents) error {
...
+	}
+
+	for i, machine := range machines {
+		data, err := yaml.Marshal(machine)
+		if err != nil {
+			return errors.Wrapf(err, "marshal master %d", i)
+		}
+
+		m.FileList = append(m.FileList, &asset.File{
+			Filename: filepath.Join(directory, fmt.Sprintf(MasterMachineFileName, strconv.Itoa(i))),
```
Comment (staebler) [inline pkg/asset/machines/master.go]: Can you change the `%s` to `%v` in `MasterMachineFileName` and get rid of the `strconv.Itoa` call?

File: pkg/asset/machines/master.go [hunk 2]
```diff
@@ -114,9 +135,108 @@ func (m *Master) Generate(dependencies asset.Parents) error {
...
+
+		switch providerType.APIVersion {
+		case "awsproviderconfig.k8s.io/v1alpha1":
+			provider := &awsprovider.AWSMachineProviderConfig{}
+			err = yaml.Unmarshal(rawProvider, &provider)
+			if err != nil {
+				return true, errors.Wrapf(err, "unmarshal %s AWS provider", file.Filename)
+			}
+			machine.Spec.ProviderSpec.Value = &runtime.RawExtension{Object: provider}
+			m.Machines = append(m.Machines, *machine)
```
Comment (staebler) [inline pkg/asset/machines/master.go]: If there are more than 10 machines, then the order of the machines in the slice will not be preserved when loaded back in. This will cause the asset store to think that the asset is dirty.

**Comment by wking** [comment]
> I don't have a better solution for you...

Ok.  Should be fixed using your approach with 7f61d57 -> d5c01c0.

File: pkg/asset/machines/master.go [hunk 3]
```diff
@@ -114,9 +138,110 @@ func (m *Master) Generate(dependencies asset.Parents) error {
...
+		if os.IsNotExist(err) {
+			return false, nil
+		}
+		return false, err
+	}
+	m.FileList = []*asset.File{file}
+
+	m.Machines = []machineapi.Machine{}
+	m.MachinesDeprecated = []clusterapi.Machine{}
+	fileList, err := f.FetchByPattern(filepath.Join(directory, fmt.Sprintf(MasterMachineFileName, "*")))
```
Comment (staebler) [inline pkg/asset/machines/master.go]: We should return `false` if there are no master machine files since we require at least one master machine.

File: pkg/asset/machines/master.go [hunk 4]
```diff
@@ -114,9 +138,110 @@ func (m *Master) Generate(dependencies asset.Parents) error {
 	default:
 		return fmt.Errorf("invalid Platform")
 	}
+
+	machines := []interface{}{}
+	if len(m.Machines) == 0 {
```
Comment (staebler) [inline pkg/asset/machines/master.go]: You don't even need to do this check. You can add from both `Machines` and `MachineDeprecated`.

File: pkg/asset/machines/master.go [hunk 5]
```diff
@@ -114,9 +138,110 @@ func (m *Master) Generate(dependencies asset.Parents) error {
...
+
+	m.Machines = []machineapi.Machine{}
+	m.MachinesDeprecated = []clusterapi.Machine{}
+	fileList, err := f.FetchByPattern(filepath.Join(directory, fmt.Sprintf(MasterMachineFileName, "*")))
+	if err != nil {
+		return true, err
+	}
+	m.FileList = append(m.FileList, fileList...)
+	for _, file := range fileList {
+		machine := &machineapi.Machine{}
```
Comment (staebler) [inline pkg/asset/machines/master.go]: Are we comfortable that a `clusterapi.Machine` will successfully unmarshal into a `machineapi.Machine`? The safer approach would be to unmarshal into a `map[string]interface{}` first and inspect the `apiVersion` field.

File: pkg/asset/machines/master.go (hunk 2 above)
Comment (wking) [reply pkg/asset/machines/master.go]: > If there are more than 10 machines, then the order of the machines in the slice will not be preserved when loaded back in.

I sort [here][1] and [here][2] to guard against that.

[1]: https://github.com/wking/openshift-installer/commit/d5c01c0ef2d016b30ba750e97bc17db96f30f129#diff-66b4febb36af0238bb6c09e72c1c44ecR165
[2]: https://github.com/wking/openshift-installer/commit/d5c01c0ef2d016b30ba750e97bc17db96f30f129#diff-66b4febb36af0238bb6c09e72c1c44ecR241

Comment (staebler) [reply pkg/asset/machines/master.go]: Those sort `FileList` but do nothing for `Machines` or `MachinesDeprecated`.

Let's say that there are 11 machines. The machines will be loaded into `Machines` in this order: 0, 1, 10, 2, 3, 4, 5, 6, 7, 8, 9. That will be different than the numerical order that they were in when the asset was generated.

File: pkg/asset/machines/master.go (hunk 3 above)
Comment (wking) [reply pkg/asset/machines/master.go]: > We should return `false` if there are no master machine files since we require at least one master machine.

If we find a master user-data file but no master machines, we currently return "succesfully loaded" here (because we did successfully load part of the asset), and then later on error out over [here][1], to avoid `[0]` access panics.  I think we want to keep that guard, so we don't *need* another guard here.

If you're trying to trigger a regeneration instead of error out, I think we'd need to split master user-data out into it's own asset.  I'm fine with that (#556 takes this to its inevitable, asset-for-every-file conclusion), but I'd rather punt on it for this PR ;).

[1]: https://github.com/wking/openshift-installer/blob/d5c01c0ef2d016b30ba750e97bc17db96f30f129/pkg/asset/cluster/tfvars.go#L102-L103

File: pkg/asset/machines/master.go (hunk 5 above)
Comment (staebler) [reply pkg/asset/machines/master.go]: Or into a `runtime.TypeMeta` like you do to get the provider type.

File: pkg/asset/machines/master.go (hunk 4 above)
Comment (wking) [reply pkg/asset/machines/master.go]: > You can add from both `Machines` and `MachineDeprecated`.

Hopefully `MachinesDeprecated` doesn't survive the week, so it's probably not worth quibbling over ;).  But I've taken the approach I have so I can just kill lines and drop tabs for most of the removal (just OpenStack to go).  Is that convincing enough, or did you want me to make this adjutment to satisfy you in the short term?

File: pkg/asset/machines/master.go (hunk 3 above)
Comment (staebler) [reply pkg/asset/machines/master.go]: My preference is that each asset enforces its out invariants. It is an invariant of the `machines.Master` asset that there is at least one master. That asset should be the one that is complaining when the invariant is not met. I am fine with returning an instead of returning `false`, but I would like this `Load` function to be the one returning the error.

File: pkg/asset/machines/master.go (hunk 5 above)
Comment (wking) [reply pkg/asset/machines/master.go]: > The safer approach would be to unmarshal into a `map[string]interface{}` first and inspect the `apiVersion` field.

Currently:

```console
$ head -n1 wking/openshift/99_openshift-cluster-api_master-machines-0.yaml 
apiVersion: 5
trking@trking ~/.local/lib/go/src/github.com/openshift/installer $ openshift-install --dir=wking create ignition-configs
FATAL failed to fetch Bootstrap Ignition Config: failed to load asset "Master Machines": unmarshal "openshift/99_openshift-cluster-api_master-machines-0.yaml": error unmarshaling JSON: json: cannot unmarshal number into Go struct field Machine.apiVersion of type string 
```

I think that's useful validation (and it covers the rest of the structure, except the opaque-at-this-stage provider spec, which we unmarshal a few lines down).  Using `interface{}`-style marshalling would give us the opportunity to customise error messages, but I think the above error is clear enough that I'm not excited about sinking time into the interface approach ;).  Thoughts?

File: pkg/asset/machines/master.go (hunk 3 above)
Comment (staebler) [reply pkg/asset/machines/master.go]: Compare it to how loading works for the `InstallConfig` asset. If the user sets the master replicas to 0 in `install-config.yaml`, then loading the `InstallConfig` asset fails. The installer does not wait until some later asset tries to use the replica count to decide that a value of 0 is not valid.

File: pkg/asset/machines/master.go (hunk 1 above)
Comment (wking) [reply pkg/asset/machines/master.go]: > Can you change the `%s` to `%v`...

:man_facepalming: Done with d5c01c0 -> 1c0796a.

File: pkg/asset/machines/master.go (hunk 4 above)
Comment (staebler) [reply pkg/asset/machines/master.go]: I am fine with making no changes here. It was just a suggestion.

File: pkg/asset/machines/master.go (hunk 5 above)
Comment (staebler) [reply pkg/asset/machines/master.go]: I am confused about what you are showing me here and what the conclusion is. I was expecting that `apiVersion` was either `machine.openshift.io/v1beta1` or `cluster.k8s.io/v1alpha1`, not `5`. However, you are comfortable that an openstack master machine file can subsequently be unmarshaled into a `machineapi.Machine` enough to determine the provider type, then I am satisfied.

Comment (wking) [reply pkg/asset/machines/master.go]: > I was expecting that `apiVersion` was either `machine.openshift.io/v1beta1` or `cluster.k8s.io/v1alpha1`, not `5`. 

I was trying to show what errors looked like when unmarshal failed (to cover your "safer" concerns).

> However, if you are comfortable that an openstack master machine file can subsequently be unmarshaled into a machineapi.Machine enough to determine the provider type, then I am satisfied.

I'm don't have an OpenStack account to test with, so I get:

```console
$ cat wking/install-config.yaml
apiVersion: v1beta2
baseDomain: devcluster.openshift.com
metadata:
  name: wking
platform:
  openstack: {}
pullSecret: ...redacted...
$ openshift-install --dir=wking create manifests
FATAL failed to fetch Master Machines: failed to load asset "Install Config": invalid "install-config.yaml" file: platform.openstack.cloud: Internal error: could not retrieve valid clouds 
```

Maybe @flaper87 or @tomassedovic can give this PR a spin on OpenStack to let us know if:

```console
$ openshift-install --dir=wking create manifests
$ openshift-install --dir=wking create ignition-configs
```

works?  In the mean time, I'll see if I can hack around the missing stuff to get my installer to generate OpenStack Machine configs.

File: pkg/asset/machines/master.go [hunk 6]
```diff
@@ -114,9 +137,110 @@ func (m *Master) Generate(dependencies asset.Parents) error {
...
+			machine.Spec.ProviderSpec.Value = &runtime.RawExtension{Object: provider}
+			m.Machines = append(m.Machines, *machine)
+		case "libvirtproviderconfig.k8s.io/v1alpha1":
+			provider := &libvirtprovider.LibvirtMachineProviderConfig{}
+			err = yaml.Unmarshal(rawProvider, &provider)
+			if err != nil {
+				return true, errors.Wrapf(err, "unmarshal %s libvirt provider", file.Filename)
+			}
+			m.Machines = append(m.Machines, *machine)
+		case "openstack.cluster.k8s.io/v1alpha1":
```
Comment (staebler) [inline pkg/asset/machines/master.go]: This should be `openstackproviderconfig.k8s.io/v1alpha1`.

File: pkg/asset/machines/master.go (hunk 5 above)
Comment (staebler) [reply pkg/asset/machines/master.go]: I was able to generate the following `99_openshift-cluster-api_master-machines-0.yaml` file for an OpenStack machine. The installer was able to load it successfully. If we are comfortable this the deprecated machines are temporary and we will not keep this code through as `clusterapi` and `machineapi` drift apart, then I am fine with the code as is.

```
apiVersion: cluster.k8s.io/v1alpha1
kind: Machine
metadata:
  creationTimestamp: null
  labels:
    sigs.k8s.io/cluster-api-cluster: mstaeble
    sigs.k8s.io/cluster-api-machine-role: master
    sigs.k8s.io/cluster-api-machine-type: master
  name: mstaeble-master-0
  namespace: openshift-cluster-api
spec:
  metadata:
    creationTimestamp: null
  providerSpec:
    value:
      apiVersion: openstackproviderconfig.k8s.io/v1alpha1
      cloudName: openstack
      cloudsSecret:
        name: openstack-credentials
        namespace: kube-system
      flavor: myFlavor
      image: rhcos
      kind: OpenstackProviderSpec
      networks:
      - filter:
          tags: openshiftClusterID=653b7d0d-c273-4007-a39a-155ab2ca5e9d
      root_volume:
        volumeType: ""
      securityGroups:
      - master
      userDataSecret:
        name: master-user-data
  versions:
    kubelet: ""
status: {}
```

File: pkg/asset/machines/master.go (hunk 2 above)
Comment (wking) [reply pkg/asset/machines/master.go]: > Those sort FileList but do nothing for `Machines` or `MachinesDeprecated`.

Ah, right.  I've pushed 1c0796a -> 24aa42f addressing this.  Notes on the padded-index calculations in the new commit message.

File: pkg/asset/machines/master.go (hunk 6 above)
Comment (wking) [reply pkg/asset/machines/master.go]: > This should be `openstackproviderconfig.k8s.io/v1alpha1`.

Oops, thanks :).  Fixed in 24aa42f -> 955cf95.

File: pkg/asset/machines/master.go (hunk 3 above)
Comment (wking) [reply pkg/asset/machines/master.go]: > It is an invariant of the `machines.Master` asset that there is at least one master. That asset should be the one that is complaining when the invariant is not met. I am fine with returning an instead of returning false, but I would like this `Load` function to be the one returning the error.

Guards (like "`len(mySlice) > 0`?") that live far from the action they're guarding (like `mySlice[0]`) are only reliable when you stay on top of the call-chain to ensure all access to the guarded code passes through the guard.  I'm fine with belt-and-suspenders guards in both places, but I don't think we should drop the local guards that live right before the guarded action.  I've pushed 955cf95 -> 1e32e76 adding a `Master.Load` guard which will generate error messages like:

```
FATAL failed to fetch Bootstrap Ignition Config: failed to load asset "Master Machines": master machine manifests are required if you also provide openshift/99_openshift-cluster-api_master-user-data-secret.yaml 
```

**Comment by staebler** [comment]
Wondering why hive was having problems with this panic led me to the realization that this PR does not completely solve the problem. The following will still panic, because loading from the state file will keep the provider config as raw json.

`openshift-install create ignition-config`
`openshift-install create cluster`

File: pkg/asset/machines/master.go (hunk 5 above)
Comment (wking) [reply pkg/asset/machines/master.go]: > In the mean time, I'll see if I can hack around the missing stuff...

With

```diff
diff --git a/pkg/asset/installconfig/platformcredscheck.go b/pkg/asset/installconfig/platformcredscheck.go
index 671ae14..8e78456 100644
--- a/pkg/asset/installconfig/platformcredscheck.go
+++ b/pkg/asset/installconfig/platformcredscheck.go
@@ -30,2 +30,3 @@ func (a *PlatformCredsCheck) Dependencies() []asset.Asset {
 func (a *PlatformCredsCheck) Generate(dependencies asset.Parents) error {
+	return nil
 	ic := &InstallConfig{}
diff --git a/pkg/asset/manifests/openshift.go b/pkg/asset/manifests/openshift.go
index c63a9d7..f67d8dd 100644
--- a/pkg/asset/manifests/openshift.go
+++ b/pkg/asset/manifests/openshift.go
@@ -15,5 +15,5 @@ import (
 	// https://github.com/openshift/installer/pull/854
-	goyaml "gopkg.in/yaml.v2"
+//	goyaml "gopkg.in/yaml.v2"
 
-	"github.com/gophercloud/utils/openstack/clientconfig"
+//	"github.com/gophercloud/utils/openstack/clientconfig"
 	"github.com/openshift/installer/pkg/asset"
@@ -21,3 +21,3 @@ import (
 	"github.com/openshift/installer/pkg/asset/machines"
-	osmachine "github.com/openshift/installer/pkg/asset/machines/openstack"
+//	osmachine "github.com/openshift/installer/pkg/asset/machines/openstack"
 	"github.com/openshift/installer/pkg/asset/password"
@@ -85,2 +85,3 @@ func (o *Openshift) Generate(dependencies asset.Parents) error {
 	case "openstack":
+/*
 		opts := new(clientconfig.ClientOpts)
@@ -107,2 +108,3 @@ func (o *Openshift) Generate(dependencies asset.Parents) error {
 		}
+*/
 	}
diff --git a/pkg/types/openstack/validation/platform.go b/pkg/types/openstack/validation/platform.go
index 1217978..4b5a662 100644
--- a/pkg/types/openstack/validation/platform.go
+++ b/pkg/types/openstack/validation/platform.go
@@ -13,2 +13,3 @@ func ValidatePlatform(p *openstack.Platform, fldPath *field.Path, fetcher ValidV
 	allErrs := field.ErrorList{}
+	return allErrs
 	validClouds, err := fetcher.GetCloudNames()

```

and [my earlier `install-config.yaml`][1], I can generate `openshift/99_openshift-cluster-api_master-machines-0.yaml` like:

```yaml
apiVersion: cluster.k8s.io/v1alpha1
kind: Machine
metadata:
  creationTimestamp: null
  labels:
    sigs.k8s.io/cluster-api-cluster: wking
    sigs.k8s.io/cluster-api-machine-role: master
    sigs.k8s.io/cluster-api-machine-type: master
  name: wking-master-0
  namespace: openshift-cluster-api
spec:
  metadata:
    creationTimestamp: null
  providerSpec:
    value:
      apiVersion: openstackproviderconfig.k8s.io/v1alpha1
      cloudName: openstack
      cloudsSecret:
        name: openstack-credentials
        namespace: kube-system
      flavor: ""
      image: rhcos
      kind: OpenstackProviderSpec
      networks:
      - filter:
          tags: openshiftClusterID=6b7a511b-e595-4077-95fa-11cd058f70e0
      root_volume:
        volumeType: ""
      securityGroups:
      - master
      userDataSecret:
        name: master-user-data
  versions:
    kubelet: ""
status: {}
```

A subsequent `openshift-install --dir=wking create ignition-configs` sucks them back in without crashing, so I think we're good here.  @staebler, did you want me to check anything else in this space?

[1]: https://github.com/openshift/installer/pull/1211#discussion_r255217192

**Comment by wking** [comment]
> The following will still panic, because loading from the state file will keep the provider config as raw json.

Do we have hooks to deserialize when we load from the state file?  If not, maybe we just need to throw in the towel on serialized asset structures (which will make @abhinavdahiya sad ;).

File: pkg/asset/machines/master.go (hunk 3 above)
Comment (staebler) [reply pkg/asset/machines/master.go]: I can live with that.

My opinion on the matter is that the later error is a code error rather than a user error. Whether the installer panics at that point or displays a less jarring error, it is still a failure if the user sees it. I don't see much value in carrying around the code for the extra guard to catch a code error. The guard is not even sufficient to protect against running over the bounds of the slice because there is no guarantee that `masterCount` came from length of the slice being accessed. It could be that `MachinesDeprecated` had a positive length while `Machines` had a zero length, even though the platform is AWS.

**Comment by staebler** [comment]
> > The following will still panic, because loading from the state file will keep the provider config as raw json.
> 
> Do we have hooks to deserialize when we load from the state file? If not, maybe we just need to throw in the towel on structured asset properties (which will make @abhinavdahiya sad ;).

No hooks.

File: pkg/asset/machines/master.go (hunk 5 above)
Comment (staebler) [reply pkg/asset/machines/master.go]: Nope. I am fine with this if we are sure that `MachineDeprecated` will expire soon.

**Comment by staebler** [comment]
> > The following will still panic, because loading from the state file will keep the provider config as raw json.
> 
> Do we have hooks to deserialize when we load from the state file? If not, maybe we just need to throw in the towel on structured asset properties (which will make @abhinavdahiya sad ;).

What if we remove the `Machines` and `MachineDeprecated` fields and instead have `Machines` and `MachineDeprecated` functions that do the loading from the raw bytes when needed? It is maybe not as neat, but it should be roughly the same amount of code.

**Comment by wking** [comment]
> What if we remove the `Machines` and `MachineDeprecated` fields and instead have `Machines` and `MachineDeprecated` functions that do the loading from the raw bytes when needed?

I don't have strong opinions on whether the deserializing code lives in `Master` methods or locally in the `TerraformVariables` asset or the `TFVars` conversion code that is our only consumer of the structured data.  And I'm personally fine with this approach, but @abhinavdahiya had previous concerns about the inefficiency of washing to bytes and back for the case when the user is going straight from the structured generated code into Terraform variable generation (e.g. [here][1]).

[1]: https://github.com/openshift/installer/pull/792#discussion_r239234108

**Comment by wking** [comment]
Ok, I've pushed 1e32e76 -> 3fd7e2b shifting to unmarshalling `Master` methods.  I still need to work in some `runtime.Decode` changes @abhinavdahiya suggested, but I thought I'd push so folks could look at the new approach (`runtime.Decode` will just be a local change in the unmarshalling methods).

**Comment by wking** [comment]
[e2e-aws was close][1]:

```
Flaky tests:

[Feature:Builds][Conformance] s2i build with a quota  Building from a template should create an s2i build with a quota and run it [Suite:openshift/conformance/parallel/minimal]

Failing tests:

[Feature:Platform] Managed cluster should have no crashlooping pods in core namespaces over two minutes [Suite:openshift/conformance/parallel]
```

I've just pushed 3fd7e2b -> 6b0bd4b with the pivot to `runtime.Decode`, CC @abhinavdahiya.

[1]: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/1211/pull-ci-openshift-installer-master-e2e-aws/3549/build-log.txt

**Comment by abhinavdahiya** [comment]
will https://github.com/openshift/installer/pull/1223 affect the Decode ?

**Comment by wking** [comment]
> will #1223 affect the Decode ?

Sigh.  Maybe?  I guess for that I need to bump our vendor around openshift/cluster-api-provider-aws#152.

**Comment by wking** [comment]
Rebased around #1223 and bumped our vendored AWS-provider code from v1alpha1 to v1beta1 with 2f16fa5 -> d983eae.  I haven't tested it though, although I guess CI will help with that.

**Comment by abhinavdahiya** [comment]
api requests getting [rate-limited](https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_installer/1211/pull-ci-openshift-installer-master-e2e-aws/3581)
```console
level=error msg="Error: Error applying plan:"
level=error
level=error msg="5 errors occurred:"
level=error msg="\t* module.vpc.aws_lb.api_external: 1 error occurred:"
level=error msg="\t* aws_lb.api_external: timeout while waiting for state to become 'active' (last state: 'provisioning', timeout: 10m0s)"
level=error
level=error
level=error msg="\t* module.vpc.aws_lb.api_internal: 1 error occurred:"
level=error msg="\t* aws_lb.api_internal: timeout while waiting for state to become 'active' (last state: 'provisioning', timeout: 10m0s)"
level=error
level=error
level=error msg="\t* module.vpc.aws_route_table_association.route_net[2]: 1 error occurred:"
level=error msg="\t* aws_route_table_association.route_net.2: timeout while waiting for state to become 'success' (timeout: 5m0s)"
level=error
level=error
level=error msg="\t* module.vpc.aws_route_table_association.route_net[3]: 1 error occurred:"
level=error msg="\t* aws_route_table_association.route_net.3: timeout while waiting for state to become 'success' (timeout: 5m0s)"
level=error
level=error
level=error msg="\t* module.vpc.aws_route.igw_route: 1 error occurred:"
level=error msg="\t* aws_route.igw_route: Error creating route: timeout while waiting for state to become 'success' (timeout: 2m0s)"
```

will retest in some time.

**Comment by dgoodwin** [comment]
/test e2e-aws

Hive CI still totally blocked on this. :(

**Comment by abhinavdahiya** [comment]
The tests are green..

/lgtm
