### PR TITLE
pkg/executor: fix executable path lookup

### LINKED ISSUE #210: the shipped terraform is not used when the installer is called via PATH lookup
I ran into this issue trying to destroy a libvirt cluster:

```
$ tectonic destroy --dir=test1

Error:
Terraform doesn't allow running any operations against a state
that was written by a future Terraform version. The state is
reporting it is written by Terraform '0.11.7'

Please run at least that version of Terraform to continue.
```

Between create and destroy, I have installed terraform to my PATH.
I suspect there is something odd in the [logic to find the terraform binary][1], as removing it from PATH makes the error go away and succeed in destroying the cluster.

[1]: https://github.com/steveeJ/installer/commit/b95525199cbc7b5f8d531befe0f2b7e94a7748e5#diff-ea8bd5729880215853a015ccaaae64b1R76

### PR DESCRIPTION
**Pull request by steveeJ**
Fixes #210.

/cc @enxebre

### CODE REVIEW

**Comment by wking** [comment]
This looks good to me (although note [the `os.Executable` caveats][1]).  If we trust this change (and I do so far ;), can we drop [the `PATH` export suggestions][2] to simplify life for folks running from a tarball?

[1]: https://golang.org/pkg/os/#Executable
[2]: https://github.com/openshift/installer/issues/210#issuecomment-419213361

**Comment by steveeJ** [comment]
> This looks good to me (although note the os.Executable caveats).
I have tried to reproduce any weird behavior when the binary or its directory are symlinks, and `os.Executable()` succeeded in evaluating the real path in both cases. Maybe the behavior is different on Mac or Windows, but I can't easily verify that at this point. 

> If we trust this change (and I do so far ;), can we drop the PATH export suggestions to simplify life for folks running from a tarball?

We could replace it with a TECTONIC variable just for the binary itself..

**Comment by wking** [comment]
Can you extend 7fed6079 to cover the [other locations][1] where we suggest altering `PATH` (`README.md` and `tests/run.sh`)?

[1]: https://github.com/openshift/installer/issues/210#issuecomment-419213361

**Comment by steveeJ** [comment]
> Can you extend 7fed607 to cover the other locations where we suggest altering PATH (README.md and tests/run.sh)?

How about an alias instead?

```sh
alias tectonic="${PWD}/tectonic-dev/installer/tectonic"
```

**Comment by wking** [comment]
> How about an alias instead?

That's fine with me, so I'm good with this PR if you squash 995d5ff9e in.  I haven't seen a script using  `alias` internally before though, so I'd also be fine with you updating `tests/run.sh` to use absolute paths when it needs to call `tectonic`.  Whichever way you like best.

File: tests/run.sh [hunk 1]
```diff
@@ -33,7 +33,7 @@ bazel build tarball smoke_tests
 echo -e "\\e[36m Unpacking artifacts...\\e[0m"
 tar -zxf bazel-bin/tectonic-dev.tar.gz
 cp bazel-bin/tests/smoke/linux_amd64_stripped/go_default_test tectonic-dev/smoke
-export PATH="${PWD}/tectonic-dev/installer:${PATH}"
+alias tectonic="${PWD}/tectonic-dev/installer/tectonic"
```
[the remark this answers is not in the document]
Comment (wking) [reply tests/run.sh]: > The alternative would be to store the path in a variable and call it with a $, but that takes away copy and paste compatibility between the script and the terminal, and otherwise has no improvement other than ShellCheck being tricked.

Another alternative is:

```sh
"${PWD}/installer/tectonic" init --config="${CLUSTER_NAME}".yaml
```

and similarly for the other invocations.  You can paste that into a terminal, and it's not tricking ShellCheck.

**Comment by steveeJ** [comment]
Guess what: I've ran into trouble with the aliases when testing :-)
Holding it for now.

/hold

File: tests/run.sh [hunk 2]
```diff
@@ -18,7 +18,7 @@ exec &> >(tee -a "$CLUSTER_NAME.log")
 
 function destroy() {
   echo -e "\\e[34m Exiting... Destroying Tectonic...\\e[0m"
-  tectonic destroy --dir="${CLUSTER_NAME}"
+  $tectonic destroy --dir="${CLUSTER_NAME}"
```
Comment (wking) [inline tests/run.sh]: I'm surprised that ShellCheck is fine with this unquoted expansion.  Can you quote it with an uppercase variable name, or use `installer/tectonic` instead of the variable?  Using `installer/tectonic` would also give you the "copy/paste the tail end of the line to get `tectonic ...` for pasting into a shell" which may be your motivation for the lowercase variable.

Comment (steveeJ) [reply tests/run.sh]: So back to how it was 3 iterations ago before aliases came to my mind. FWIW, aliases would've worked but with the caveat of having to define it before any function definition which makes use of the alias.

File: tests/run.sh [hunk 3]
```diff
@@ -18,7 +18,7 @@ exec &> >(tee -a "$CLUSTER_NAME.log")
 
 function destroy() {
   echo -e "\\e[34m Exiting... Destroying Tectonic...\\e[0m"
-  tectonic destroy --dir="${CLUSTER_NAME}"
+  "${TECTONIC}" destroy --dir="${CLUSTER_NAME}"
```
Comment (wking) [inline tests/run.sh]: This doesn't seem to work either:

```console
$ git describe --always --dirty
2d3306a-dirty
$ git diff
diff --git a/tests/run.sh b/tests/run.sh
index 407e594..22373c0 100755
--- a/tests/run.sh
+++ b/tests/run.sh
@@ -26,6 +26,7 @@ function destroy() {
 trap destroy EXIT
 
 echo -e "\\e[36m Starting build process...\\e[0m"
+exit  # FIXME: just for testing
 bazel build tarball smoke_tests
 # In future bazel build could be extracted to another job which could be running in docker container like this:
 # docker run --rm -v $PWD:$PWD:Z -w $PWD quay.io/coreos/tectonic-builder:bazel-v0.3 bazel build tarball smoke_tests
$ PULL_SECRET_PATH=~/src/openshift/installer/pull-secret.json tests/run.sh 
 Starting build process...
 Exiting... Destroying Tectonic...
tests/run.sh: line 21: : command not found
```

Things that do work:

```diff
diff --git a/tests/run.sh b/tests/run.sh
index 407e594..f74d94f 100755
--- a/tests/run.sh
+++ b/tests/run.sh
@@ -16,6 +16,8 @@ SMOKE_TEST_OUTPUT="Never executed. Problem with one of previous stages"
 CLUSTER_NAME=$(echo "${PREFIX}-$(uuidgen -r | cut -c1-5)" | tr '[:upper:]' '[:lower:]')
 exec &> >(tee -a "$CLUSTER_NAME.log")
 
+TECTONIC="${PWD}/tectonic-dev/installer/tectonic"
+
 function destroy() {
   echo -e "\\e[34m Exiting... Destroying Tectonic...\\e[0m"
   "${TECTONIC}" destroy --dir="${CLUSTER_NAME}"
@@ -26,6 +28,7 @@ function destroy() {
 trap destroy EXIT
 
 echo -e "\\e[36m Starting build process...\\e[0m"
+exit  # FIXME: just for testing
 bazel build tarball smoke_tests
 # In future bazel build could be extracted to another job which could be running in docker container like this:
 # docker run --rm -v $PWD:$PWD:Z -w $PWD quay.io/coreos/tectonic-builder:bazel-v0.3 bazel build tarball smoke_tests
@@ -33,7 +36,6 @@ bazel build tarball smoke_tests
 echo -e "\\e[36m Unpacking artifacts...\\e[0m"
 tar -zxf bazel-bin/tectonic-dev.tar.gz
 cp bazel-bin/tests/smoke/linux_amd64_stripped/go_default_test tectonic-dev/smoke
-export TECTONIC="${PWD}/tectonic-dev/installer/tectonic"
 cd tectonic-dev
 
 ### HANDLE SSH KEY ###
```

or

```diff
diff --git a/tests/run.sh b/tests/run.sh
index 407e594..236de0e 100755
--- a/tests/run.sh
+++ b/tests/run.sh
@@ -23,8 +23,6 @@ function destroy() {
   echo -e "\\e[34m So Long, and Thanks for All the Fish\\e[0m"
 }
 
-trap destroy EXIT
-
 echo -e "\\e[36m Starting build process...\\e[0m"
 bazel build tarball smoke_tests
 # In future bazel build could be extracted to another job which could be running in docker container like this:
@@ -33,9 +31,12 @@ bazel build tarball smoke_tests
 echo -e "\\e[36m Unpacking artifacts...\\e[0m"
 tar -zxf bazel-bin/tectonic-dev.tar.gz
 cp bazel-bin/tests/smoke/linux_amd64_stripped/go_default_test tectonic-dev/smoke
-export TECTONIC="${PWD}/tectonic-dev/installer/tectonic"
 cd tectonic-dev
 
+export TECTONIC="${PWD}/installer/tectonic"
+trap destroy EXIT
+exit  # FIXME: just for testing
+
 ### HANDLE SSH KEY ###
 if [ ! -f ~/.ssh/id_rsa.pub ]; then
   echo -e "\\e[36m Generating SSH key-pair...\\e[0m"
```

or

```diff
diff --git a/tests/run.sh b/tests/run.sh
index 407e594..487b76f 100755
--- a/tests/run.sh
+++ b/tests/run.sh
@@ -18,13 +18,11 @@ exec &> >(tee -a "$CLUSTER_NAME.log")
 
 function destroy() {
   echo -e "\\e[34m Exiting... Destroying Tectonic...\\e[0m"
-  "${TECTONIC}" destroy --dir="${CLUSTER_NAME}"
+  installer/tectonic destroy --dir="${CLUSTER_NAME}"
   echo -e "\\e[36m Finished! Smoke test output:\\e[0m ${SMOKE_TEST_OUTPUT}"
   echo -e "\\e[34m So Long, and Thanks for All the Fish\\e[0m"
 }
 
-trap destroy EXIT
-
 echo -e "\\e[36m Starting build process...\\e[0m"
 bazel build tarball smoke_tests
 # In future bazel build could be extracted to another job which could be running in docker container like this:
@@ -33,9 +31,11 @@ bazel build tarball smoke_tests
 echo -e "\\e[36m Unpacking artifacts...\\e[0m"
 tar -zxf bazel-bin/tectonic-dev.tar.gz
 cp bazel-bin/tests/smoke/linux_amd64_stripped/go_default_test tectonic-dev/smoke
-export TECTONIC="${PWD}/tectonic-dev/installer/tectonic"
 cd tectonic-dev
 
+trap destroy EXIT
+exit  # FIXME
+
 ### HANDLE SSH KEY ###
 if [ ! -f ~/.ssh/id_rsa.pub ]; then
   echo -e "\\e[36m Generating SSH key-pair...\\e[0m"
@@ -91,10 +91,10 @@ python <<-EOF >"${CLUSTER_NAME}.yaml"
 	EOF
 
 echo -e "\\e[36m Initializing Tectonic...\\e[0m"
-"${TECTONIC}" init --config="${CLUSTER_NAME}".yaml
+installer/tectonic init --config="${CLUSTER_NAME}".yaml
 
 echo -e "\\e[36m Deploying Tectonic...\\e[0m"
-"${TECTONIC}" install --dir="${CLUSTER_NAME}"
+installer/tectonic install --dir="${CLUSTER_NAME}"
 echo -e "\\e[36m Running smoke test...\\e[0m"
 export SMOKE_KUBECONFIG="${PWD}/${CLUSTER_NAME}/generated/auth/kubeconfig"
 export SMOKE_NODE_COUNT="5"  # Sum of all nodes (master + worker)
```

Comment (steveeJ) [reply tests/run.sh]: I moved the variable to the others in the front

**Comment by wking** [comment]
[The tf-fmt job][1] looks like a success to me.  Not sure why GitHub gives it an x here.  Kicking it again:

/test tf-fmt

[1]: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_installer/224/pull-ci-openshift-installer-tf-fmt/162
