### PR TITLE
asset/installconfig: improve validation of user inputs

### LINKED ISSUE #910: No validation of config in `create ignition-configs`
If the user brings in an incorrect install-config (e.g. `metadata.name` is empty or `baseDomain` is empty) and runs `create ignition-configs` the config is not validated. This would make bootstrap node breaks at some point, but this could be easily prevented by validating the configs first

### PR DESCRIPTION
**Pull request by staebler**
For most of the validation, bespoke code has been removed in lieu of calling code that already exists and is more widely used.

* **Base Domain**: Use kubernetes validation of rfc-1123 sub-domains, with the addition that the base domain can end with a dot. This change removes the ability to use uppercase letters in the base domain.
* **Cluster Name**: Use kubernetes validation of rfc-1123 sub-domains. This change removes the restriction that each label in the cluster name is at most 63 characters long.
* **Pull Secret**: Validate that (1) there is an "auths" field, (2) the "auths" value has fields, and (3) each field in the "auth" value has an "auth" or a "credsStore" field.
* **SSH Public Key**: Use ParseAuthorizedKey from golang.org/x/crypto/ssh to validate that the provided ssh key can be parsed.

Validation has been added to the InstallConfig asset to enforce that the install-config.yml file loaded is valid. Some fields have been modified to make this easier. For example, the CIDR fields that were strings had their types changed to `ipnet.IPNet`.

Fixes https://jira.coreos.com/browse/CORS-850
Fixes https://jira.coreos.com/browse/CORS-941
Fixes #910

### CODE REVIEW

File: pkg/validate/validate_test.go [hunk 1]
```diff
@@ -249,51 +122,6 @@ func TestEmail(t *testing.T) {
 		})
 	}
 }
-func TestCIDRsDontOverlap(t *testing.T) {
```
[the remark this answers is not in the document]
Comment (staebler) [reply pkg/validate/validate_test.go]: I'll add some validation to install-config.yml.

[the remark this answers is not in the document]
Comment (abhinavdahiya) [reply pkg/validate/validate_test.go]: @staebler any progress on this?

[the remark this answers is not in the document]
Comment (staebler) [reply pkg/validate/validate_test.go]: The implementation for install-config.yml validation is done and add to this PR. I have a bunch of unit tests that I need to create for it still, so I have marked this PR as WIP while I finish those.

File: pkg/ipnet/ipnet.go [hunk 2]
```diff
@@ -70,3 +70,22 @@ func (ipnet *IPNet) UnmarshalJSON(b []byte) (err error) {
...
+	_, cidr, err := net.ParseCIDR(s)
+	if err != nil {
+		return nil, err
+	}
+	return &IPNet{IPNet: *cidr}, nil
+}
+
+// ParseCIDRMust parses a CIDR from its string representation. If the parse fails,
+// the function will panic.
+func ParseCIDRMust(s string) *IPNet {
```
Comment (abhinavdahiya) [inline pkg/ipnet/ipnet.go]: nit: `MustParseCIDR`

File: pkg/asset/installconfig/aws/aws.go [hunk 3]
```diff
@@ -12,15 +12,19 @@ import (
...
+var (
+	defaultVPCCIDR = ipnet.MustParseCIDR("10.0.0.0/16")
 )
 
 var (
-	validAWSRegions = map[string]string{
+	// ValidAWSRegions is a map of the known AWS regions. The key of the map is
+	// the short name of the region. The value of the map is the long name of
+	// the region.
+	ValidAWSRegions = map[string]string{
```
Comment (crawford) [inline pkg/asset/installconfig/aws/aws.go]: This should probably be moved down into types and imported instead of the other way around.

**Comment by eparis** [comment]
https://jira.coreos.com/browse/CORS-941

**Comment by abhinavdahiya** [comment]
@staebler commits https://github.com/openshift/installer/pull/711/commits/1971857321deaba84b8fe3107bade7a429db5162 ..  https://github.com/openshift/installer/pull/711/commits/5bddc8868f4c4afc18e20d6b7af7a4abead2a910 are /lgtm

I am a little concerned with addition of gomock and gomock generated files. 
* How do we regenerate them?
* How do we ensure they are always up to date (), new test in ci / or `go test ./...` is going to catch that?

File: pkg/asset/installconfig/filefetcher_generated_test.go [hunk 4]
```diff
@@ -0,0 +1,60 @@
+// Code generated by MockGen. DO NOT EDIT.
```
Comment (abhinavdahiya) [inline pkg/asset/installconfig/filefetcher_generated_test.go]: Also this file is same as like `mock/file_fetcher_generated.go` ?

Comment (staebler) [reply pkg/asset/installconfig/filefetcher_generated_test.go]: Yes. This file should not be here. I originally created it here before moving it to `mock/file_fetcher_generated.go` to make it available to multiple packages.

**Comment by staebler** [comment]
@abhinavdahiya Some documentation around running unit tests and re-generating mock files has been added to CONTRIBUTING.md.

File: pkg/types/validation/installconfig_test.go [hunk 5]
```diff
@@ -0,0 +1,299 @@
...
+					{
+						Name: "worker",
+					},
+				}
+				return c
+			}(),
+			valid: false,
+		},
+		{
+			name: "missing worker machine pool",
```
Comment (wking) [inline pkg/types/validation/installconfig_test.go]: Should this be allowed?  We can create worker pools as a day-2 operation, can't we?

File: pkg/types/validation/installconfig_test.go [hunk 6]
```diff
@@ -0,0 +1,299 @@
...
+				return c
+			}(),
+			valid: false,
+		},
+		{
+			name: "invalid machine pool",
+			installConfig: func() *types.InstallConfig {
+				c := validInstallConfig()
+				c.Machines = append(c.Machines, types.MachinePool{
+					Name: "other",
```
Comment (wking) [inline pkg/types/validation/installconfig_test.go]: I think we want to support this.  See [here][1].

[1]: https://github.com/openshift/installer/issues/264#issuecomment-422349518

File: pkg/types/validation/installconfig_test.go (hunk 5 above)
Comment (abhinavdahiya) [reply pkg/types/validation/installconfig_test.go]: Fo now our install fails if we do not have workers. So this is required for now.

File: pkg/types/validation/installconfig_test.go (hunk 6 above)
Comment (abhinavdahiya) [reply pkg/types/validation/installconfig_test.go]: hive team is going to be making that change soon, they can change the tests.
any right now we have nothing that supports adding these random pools.

File: pkg/types/validation/installconfig_test.go (hunk 5 above)
Comment (staebler) [reply pkg/types/validation/installconfig_test.go]: I remember it failing at one point without workers defined in the install config. That may have been resolved since I originally wrote it. I'll dig into it further, and if we succeed without workers defined, then I will file a follow-up PR.

**Comment by wking** [comment]
[Router timed out][1].

/retest

[1]: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/711/pull-ci-openshift-installer-master-e2e-aws/2335/build-log.txt
